//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.ConfigStrings", typeof(ConfigStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu cấu hình.
        /// </summary>
        public static string Authen_Group {
            get {
                return ResourceManager.GetString("Authen_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sao lưu.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu và phục hồi.
        /// </summary>
        public static string Backup_Restore_ListItem {
            get {
                return ResourceManager.GetString("Backup_Restore_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu thành công thành công !.
        /// </summary>
        public static string Backup_Successful {
            get {
                return ResourceManager.GetString("Backup_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu không thành công thành công !.
        /// </summary>
        public static string Backup_Unsuccessful {
            get {
                return ResourceManager.GetString("Backup_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục chứa hình màu không tồn tại !.
        /// </summary>
        public static string ColorPathNotExist {
            get {
                return ResourceManager.GetString("ColorPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string Config_Caption {
            get {
                return ResourceManager.GetString("Config_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin cấu hình bị lỗi !.
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không trùng với mật khẩu mới !.
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối với CSDL !.
        /// </summary>
        public static string ConnectDBNotSuccessful {
            get {
                return ResourceManager.GetString("ConnectDBNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối với cơ sở dữ liệu thành công !.
        /// </summary>
        public static string ConnectDBSuccessful {
            get {
                return ResourceManager.GetString("ConnectDBSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không đúng !.
        /// </summary>
        public static string CurrentPasswordWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cơ sở dữ liệu.
        /// </summary>
        public static string Database_FirstDatabasename {
            get {
                return ResourceManager.GetString("Database_FirstDatabasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Database_FirstPassword {
            get {
                return ResourceManager.GetString("Database_FirstPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server 1.
        /// </summary>
        public static string Database_FirstPriority {
            get {
                return ResourceManager.GetString("Database_FirstPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên server.
        /// </summary>
        public static string Database_FirstServername {
            get {
                return ResourceManager.GetString("Database_FirstServername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết nối.
        /// </summary>
        public static string Database_FirstTimeout {
            get {
                return ResourceManager.GetString("Database_FirstTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        public static string Database_FirstUsername {
            get {
                return ResourceManager.GetString("Database_FirstUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ưu tiên.
        /// </summary>
        public static string Database_GroupPriority {
            get {
                return ResourceManager.GetString("Database_GroupPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server 1.
        /// </summary>
        public static string Database_GroupServer1 {
            get {
                return ResourceManager.GetString("Database_GroupServer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server 2.
        /// </summary>
        public static string Database_GroupServer2 {
            get {
                return ResourceManager.GetString("Database_GroupServer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin kết nối.
        /// </summary>
        public static string Database_ListItem {
            get {
                return ResourceManager.GetString("Database_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cơ sở dữ liệu.
        /// </summary>
        public static string Database_SecondDatabasename {
            get {
                return ResourceManager.GetString("Database_SecondDatabasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Database_SecondPassword {
            get {
                return ResourceManager.GetString("Database_SecondPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server 2.
        /// </summary>
        public static string Database_SecondPriority {
            get {
                return ResourceManager.GetString("Database_SecondPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên server.
        /// </summary>
        public static string Database_SecondServername {
            get {
                return ResourceManager.GetString("Database_SecondServername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết nối.
        /// </summary>
        public static string Database_SecondTimeout {
            get {
                return ResourceManager.GetString("Database_SecondTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        public static string Database_SecondUsername {
            get {
                return ResourceManager.GetString("Database_SecondUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Kiểm tra kết nối.
        /// </summary>
        public static string Database_TestConnection {
            get {
                return ResourceManager.GetString("Database_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình màu.
        /// </summary>
        public static string Folder_ColorImage {
            get {
                return ResourceManager.GetString("Folder_ColorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tập tin.
        /// </summary>
        public static string Folder_FileType {
            get {
                return ResourceManager.GetString("Folder_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình đường dẫn lưu hình.
        /// </summary>
        public static string Folder_Group {
            get {
                return ResourceManager.GetString("Folder_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục lưu trữ và giao dịch.
        /// </summary>
        public static string Folder_ListItem {
            get {
                return ResourceManager.GetString("Folder_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình nhận dạng.
        /// </summary>
        public static string Folder_RecogImage {
            get {
                return ResourceManager.GetString("Folder_RecogImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chuẩn.
        /// </summary>
        public static string Folder_StandardImage {
            get {
                return ResourceManager.GetString("Folder_StandardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt tại trung tâm.
        /// </summary>
        public static string Monitor_CenterMode {
            get {
                return ResourceManager.GetString("Monitor_CenterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Monitor_GroupMode {
            get {
                return ResourceManager.GetString("Monitor_GroupMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số làn.
        /// </summary>
        public static string Monitor_LaneNum {
            get {
                return ResourceManager.GetString("Monitor_LaneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màn hình giám sát.
        /// </summary>
        public static string Monitor_ListItem {
            get {
                return ResourceManager.GetString("Monitor_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màn hình giám sát.
        /// </summary>
        public static string Monitor_MonitorGroup {
            get {
                return ResourceManager.GetString("Monitor_MonitorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm quản lý.
        /// </summary>
        public static string Monitor_Station {
            get {
                return ResourceManager.GetString("Monitor_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt tại trạm.
        /// </summary>
        public static string Monitor_StationMode {
            get {
                return ResourceManager.GetString("Monitor_StationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Real-time.
        /// </summary>
        public static string NonRealtime {
            get {
                return ResourceManager.GetString("NonRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục lưu trữ.
        /// </summary>
        public static string PathNotExist_Caption {
            get {
                return ResourceManager.GetString("PathNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time.
        /// </summary>
        public static string Realtime {
            get {
                return ResourceManager.GetString("Realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục chứa hình nhận dạng không tồn tại !.
        /// </summary>
        public static string RecogPathNotExist {
            get {
                return ResourceManager.GetString("RecogPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Phục hồi.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu lại cấu hình đã thay đổi không?.
        /// </summary>
        public static string SaveConfig {
            get {
                return ResourceManager.GetString("SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string Security_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Security_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        public static string Security_CurrentPassword {
            get {
                return ResourceManager.GetString("Security_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình bảo mật.
        /// </summary>
        public static string Security_Group {
            get {
                return ResourceManager.GetString("Security_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng bảo mật.
        /// </summary>
        public static string Security_IsSecurity {
            get {
                return ResourceManager.GetString("Security_IsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật.
        /// </summary>
        public static string Security_ListItem {
            get {
                return ResourceManager.GetString("Security_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ bảo mật.
        /// </summary>
        public static string Security_Mode {
            get {
                return ResourceManager.GetString("Security_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string Security_NewPassword {
            get {
                return ResourceManager.GetString("Security_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online HTTP Port.
        /// </summary>
        public static string Security_OnlinePort {
            get {
                return ResourceManager.GetString("Security_OnlinePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online URL.
        /// </summary>
        public static string Security_Url1 {
            get {
                return ResourceManager.GetString("Security_Url1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline URL.
        /// </summary>
        public static string Security_Url2 {
            get {
                return ResourceManager.GetString("Security_Url2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục chứa hình chuẩn không tồn tại !.
        /// </summary>
        public static string StandardPathNotExist {
            get {
                return ResourceManager.GetString("StandardPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _D.
        /// </summary>
        public static string UI_Close_ShortKey {
            get {
                return ResourceManager.GetString("UI_Close_ShortKey", resourceCulture);
            }
        }
    }
}
