//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataGridStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataGridStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.DataGridStrings", typeof(DataGridStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 10.
        /// </summary>
        public static string Lane10Header {
            get {
                return ResourceManager.GetString("Lane10Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 11.
        /// </summary>
        public static string Lane11Header {
            get {
                return ResourceManager.GetString("Lane11Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 12.
        /// </summary>
        public static string Lane12Header {
            get {
                return ResourceManager.GetString("Lane12Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 01.
        /// </summary>
        public static string Lane1Header {
            get {
                return ResourceManager.GetString("Lane1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 03.
        /// </summary>
        public static string Lane2Header {
            get {
                return ResourceManager.GetString("Lane2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 03.
        /// </summary>
        public static string Lane3Header {
            get {
                return ResourceManager.GetString("Lane3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 04.
        /// </summary>
        public static string Lane4Header {
            get {
                return ResourceManager.GetString("Lane4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 05.
        /// </summary>
        public static string Lane5Header {
            get {
                return ResourceManager.GetString("Lane5Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 06.
        /// </summary>
        public static string Lane6Header {
            get {
                return ResourceManager.GetString("Lane6Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 07.
        /// </summary>
        public static string Lane7Header {
            get {
                return ResourceManager.GetString("Lane7Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 08.
        /// </summary>
        public static string Lane8Header {
            get {
                return ResourceManager.GetString("Lane8Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn 09.
        /// </summary>
        public static string Lane9Header {
            get {
                return ResourceManager.GetString("Lane9Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thành tiền.
        /// </summary>
        public static string PriceSumLaneHeader {
            get {
                return ResourceManager.GetString("PriceSumLaneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string SumFinal {
            get {
                return ResourceManager.GetString("SumFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số lượng.
        /// </summary>
        public static string SumLaneHeader {
            get {
                return ResourceManager.GetString("SumLaneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng biểu đồ.
        /// </summary>
        public static string TabChartName {
            get {
                return ResourceManager.GetString("TabChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng bảng.
        /// </summary>
        public static string TabTableName {
            get {
                return ResourceManager.GetString("TabTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại vé.
        /// </summary>
        public static string TicketTypeHeader {
            get {
                return ResourceManager.GetString("TicketTypeHeader", resourceCulture);
            }
        }
    }
}
