//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeviceEffectString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceEffectString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.DeviceEffectString", typeof(DeviceEffectString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền còn lại.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy giao dịch.
        /// </summary>
        public static string Canceltransaction {
            get {
                return ResourceManager.GetString("Canceltransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc là muốn xóa giao dịch này ?.
        /// </summary>
        public static string CancelTransaction_MessageBox_Context {
            get {
                return ResourceManager.GetString("CancelTransaction_MessageBox_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy giao dịch.
        /// </summary>
        public static string CancelTransaction_MessageBox_Title {
            get {
                return ResourceManager.GetString("CancelTransaction_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy giao dịch thất bại !.
        /// </summary>
        public static string CancelTransactionFail {
            get {
                return ResourceManager.GetString("CancelTransactionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy giao dịch thành công !.
        /// </summary>
        public static string CancelTransactionSuccessful {
            get {
                return ResourceManager.GetString("CancelTransactionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        public static string CardCode {
            get {
                return ResourceManager.GetString("CardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn mã thiết bị !.
        /// </summary>
        public static string DeviceIsNotSelect {
            get {
                return ResourceManager.GetString("DeviceIsNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thiết bị.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên soát.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng ngày giờ sai !.
        /// </summary>
        public static string Error_DateTime {
            get {
                return ResourceManager.GetString("Error_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian {0} không được để trống !.
        /// </summary>
        public static string Error_DateTime_Null {
            get {
                return ResourceManager.GetString("Error_DateTime_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load dữ liệu bị lỗi !.
        /// </summary>
        public static string ErrorLoadData {
            get {
                return ResourceManager.GetString("ErrorLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Errror {
            get {
                return ResourceManager.GetString("Errror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết Hạn.
        /// </summary>
        public static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn.
        /// </summary>
        public static string Lane {
            get {
                return ResourceManager.GetString("Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái không có gì thay đổi !.
        /// </summary>
        public static string NoChangeStatus {
            get {
                return ResourceManager.GetString("NoChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể hủy hiệu lực thiết bị này.
        /// </summary>
        public static string NotCanCancelDeviceEffice {
            get {
                return ResourceManager.GetString("NotCanCancelDeviceEffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể chuyển trạng thái thiết bị từ trạng thái:&quot; {0} &quot; sang trạng thái &quot; {1} &quot; hay trạng thái &quot; {2} &quot; !.
        /// </summary>
        public static string NotChangeCancel_ActiveOrLock {
            get {
                return ResourceManager.GetString("NotChangeCancel_ActiveOrLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể chuyển trạng thái thiết bị từ trạng thái:&quot;  {0} &quot; sang trạng thái &quot; {1} &quot; !.
        /// </summary>
        public static string NotChangeExprie_Active {
            get {
                return ResourceManager.GetString("NotChangeExprie_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị này không tồn tại !.
        /// </summary>
        public static string NotDevice {
            get {
                return ResourceManager.GetString("NotDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thiết bị cho loại này để hủy hiệu lực !.
        /// </summary>
        public static string NotDeviceForCancelEffect {
            get {
                return ResourceManager.GetString("NotDeviceForCancelEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi hiệu lực thiết bị không thành công !.
        /// </summary>
        public static string NotExecuteDeviceEffect {
            get {
                return ResourceManager.GetString("NotExecuteDeviceEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thay đổi hiệu lực !.
        /// </summary>
        public static string NotPermissionToChange {
            get {
                return ResourceManager.GetString("NotPermissionToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu cho điều kiện thống kê bạn chọn !.
        /// </summary>
        public static string NotSearchResult {
            get {
                return ResourceManager.GetString("NotSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có trạng thái.
        /// </summary>
        public static string NotStatus {
            get {
                return ResourceManager.GetString("NotStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string ObjectDevice {
            get {
                return ResourceManager.GetString("ObjectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Đối tượng.
        /// </summary>
        public static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe nhận dạng.
        /// </summary>
        public static string RecogPlateNumber {
            get {
                return ResourceManager.GetString("RecogPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe đăng ký .
        /// </summary>
        public static string RegisPlateNumber {
            get {
                return ResourceManager.GetString("RegisPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả hậu kiểm.
        /// </summary>
        public static string ResultPostCheck {
            get {
                return ResourceManager.GetString("ResultPostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tìm kiếm giao dịch.
        /// </summary>
        public static string SearchInformationTransaction {
            get {
                return ResourceManager.GetString("SearchInformationTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string SelectedCheckBox {
            get {
                return ResourceManager.GetString("SelectedCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trạm chưa cấu hình. Hãy cấu hình trạm vì chức năng có sử dụng thông tin của trạm cấu hình !.
        /// </summary>
        public static string StationNotConfig {
            get {
                return ResourceManager.GetString("StationNotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn trạm  !.
        /// </summary>
        public static string StationNotSelect {
            get {
                return ResourceManager.GetString("StationNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hiệu lực thiết bị thành công !.
        /// </summary>
        public static string SuccessfullExecuteDeviceEffect {
            get {
                return ResourceManager.GetString("SuccessfullExecuteDeviceEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chưa được chọn !.
        /// </summary>
        public static string TimeIsnotSelect {
            get {
                return ResourceManager.GetString("TimeIsnotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của thiết bị.
        /// </summary>
        public static string TitleDeviceEffect {
            get {
                return ResourceManager.GetString("TitleDeviceEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái thiết bị.
        /// </summary>
        public static string TitleDeviceEffectView {
            get {
                return ResourceManager.GetString("TitleDeviceEffectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm thiết bị.
        /// </summary>
        public static string TitleDeviceSearchView {
            get {
                return ResourceManager.GetString("TitleDeviceSearchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn giao dịch !.
        /// </summary>
        public static string TransactionIsNotSelect {
            get {
                return ResourceManager.GetString("TransactionIsNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất Cả.
        /// </summary>
        public static string UI_All {
            get {
                return ResourceManager.GetString("UI_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy hiệu _lực thẻ.
        /// </summary>
        public static string UI_CancelDeviceEffect {
            get {
                return ResourceManager.GetString("UI_CancelDeviceEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _l.
        /// </summary>
        public static string UI_CancelDeviceEffect_Shortkey {
            get {
                return ResourceManager.GetString("UI_CancelDeviceEffect_Shortkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hủy giao dịch.
        /// </summary>
        public static string UI_CancelTransaction {
            get {
                return ResourceManager.GetString("UI_CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Thay Đổi.
        /// </summary>
        public static string UI_Change {
            get {
                return ResourceManager.GetString("UI_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _T.
        /// </summary>
        public static string UI_Change_Shortkey {
            get {
                return ResourceManager.GetString("UI_Change_Shortkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _o.
        /// </summary>
        public static string UI_Close_ShortKey {
            get {
                return ResourceManager.GetString("UI_Close_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string UI_CustomerName {
            get {
                return ResourceManager.GetString("UI_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        public static string UI_Device {
            get {
                return ResourceManager.GetString("UI_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string UI_DeviceCode {
            get {
                return ResourceManager.GetString("UI_DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thiết bị.
        /// </summary>
        public static string UI_DeviceInfor {
            get {
                return ResourceManager.GetString("UI_DeviceInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn lý do để thay đổi hiệu lưc thiết bị !.
        /// </summary>
        public static string UI_DeviceNotSelect {
            get {
                return ResourceManager.GetString("UI_DeviceNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string UI_Employee {
            get {
                return ResourceManager.GetString("UI_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ Ngày.
        /// </summary>
        public static string UI_FromDate {
            get {
                return ResourceManager.GetString("UI_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tìm kiếm giao dịch thiết bị.
        /// </summary>
        public static string UI_InforSearchDeviceTransaction {
            get {
                return ResourceManager.GetString("UI_InforSearchDeviceTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string UI_Note {
            get {
                return ResourceManager.GetString("UI_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        public static string UI_Price {
            get {
                return ResourceManager.GetString("UI_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do.
        /// </summary>
        public static string UI_Reason {
            get {
                return ResourceManager.GetString("UI_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tìm.
        /// </summary>
        public static string UI_Search {
            get {
                return ResourceManager.GetString("UI_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tìm kiếm thiết bị.
        /// </summary>
        public static string UI_SearchDeviceInfor {
            get {
                return ResourceManager.GetString("UI_SearchDeviceInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tìm Kiếm.
        /// </summary>
        public static string UI_SearchTransaction {
            get {
                return ResourceManager.GetString("UI_SearchTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Chọn tất cả.
        /// </summary>
        public static string UI_SelectAll {
            get {
                return ResourceManager.GetString("UI_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Chọn.
        /// </summary>
        public static string UI_SelectItem {
            get {
                return ResourceManager.GetString("UI_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm.
        /// </summary>
        public static string UI_Station {
            get {
                return ResourceManager.GetString("UI_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái.
        /// </summary>
        public static string UI_Status {
            get {
                return ResourceManager.GetString("UI_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến Ngày.
        /// </summary>
        public static string UI_ToDate {
            get {
                return ResourceManager.GetString("UI_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xem Chi Tiết.
        /// </summary>
        public static string UI_ViewDetail {
            get {
                return ResourceManager.GetString("UI_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phương tiện.
        /// </summary>
        public static string VehicleTypeName {
            get {
                return ResourceManager.GetString("VehicleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người hủy.
        /// </summary>
        public static string WhoCancel {
            get {
                return ResourceManager.GetString("WhoCancel", resourceCulture);
            }
        }
    }
}
