//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.ListStrings", typeof(ListStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu lại thông tin qui định kết nối mà bạn đang thao tác không ?.
        /// </summary>
        public static string Confirm_SaveConnection {
            get {
                return ResourceManager.GetString("Confirm_SaveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu lại thông tin lỗi mà bạn đang thao tác không ?.
        /// </summary>
        public static string Confirm_SaveError {
            get {
                return ResourceManager.GetString("Confirm_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu lại thông tin giá trị định mức mà bạn đang thao tác không ?.
        /// </summary>
        public static string Confirm_SaveNorm {
            get {
                return ResourceManager.GetString("Confirm_SaveNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mã kết nối.
        /// </summary>
        public static string Connection_Code_Detail {
            get {
                return ResourceManager.GetString("Connection_Code_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kết nối.
        /// </summary>
        public static string Connection_Code_List {
            get {
                return ResourceManager.GetString("Connection_Code_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui định kết nối.
        /// </summary>
        public static string Connection_ListItem {
            get {
                return ResourceManager.GetString("Connection_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tê_n kết nối.
        /// </summary>
        public static string Connection_Name_Detail {
            get {
                return ResourceManager.GetString("Connection_Name_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kết nối.
        /// </summary>
        public static string Connection_Name_List {
            get {
                return ResourceManager.GetString("Connection_Name_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ghi chú.
        /// </summary>
        public static string Connection_Note_Detail {
            get {
                return ResourceManager.GetString("Connection_Note_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Connection_Note_List {
            get {
                return ResourceManager.GetString("Connection_Note_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Số lần.
        /// </summary>
        public static string Connection_Number_Detail {
            get {
                return ResourceManager.GetString("Connection_Number_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần.
        /// </summary>
        public static string Connection_Number_List {
            get {
                return ResourceManager.GetString("Connection_Number_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_rạng thái.
        /// </summary>
        public static string Connection_State_Detail {
            get {
                return ResourceManager.GetString("Connection_State_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Connection_State_List {
            get {
                return ResourceManager.GetString("Connection_State_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gi_an kết nối.
        /// </summary>
        public static string Connection_Time_Detail {
            get {
                return ResourceManager.GetString("Connection_Time_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết nối.
        /// </summary>
        public static string Connection_Time_List {
            get {
                return ResourceManager.GetString("Connection_Time_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tạo mới.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mã lỗi.
        /// </summary>
        public static string Error_Code_Detail {
            get {
                return ResourceManager.GetString("Error_Code_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã lỗi.
        /// </summary>
        public static string Error_Code_List {
            get {
                return ResourceManager.GetString("Error_Code_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định nghĩa lỗi.
        /// </summary>
        public static string Error_ListItem {
            get {
                return ResourceManager.GetString("Error_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đ_iểm lỗi.
        /// </summary>
        public static string Error_Mark_Detail {
            get {
                return ResourceManager.GetString("Error_Mark_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm lỗi.
        /// </summary>
        public static string Error_Mark_List {
            get {
                return ResourceManager.GetString("Error_Mark_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tê_n lỗi.
        /// </summary>
        public static string Error_Name_Detail {
            get {
                return ResourceManager.GetString("Error_Name_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên lỗi.
        /// </summary>
        public static string Error_Name_List {
            get {
                return ResourceManager.GetString("Error_Name_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ghi chú.
        /// </summary>
        public static string Error_Note_Detail {
            get {
                return ResourceManager.GetString("Error_Note_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Error_Note_List {
            get {
                return ResourceManager.GetString("Error_Note_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_rạng thái.
        /// </summary>
        public static string Error_State_Detail {
            get {
                return ResourceManager.GetString("Error_State_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Error_State_List {
            get {
                return ResourceManager.GetString("Error_State_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin qui định kết nối đã được xóa khỏi hệ thống !.
        /// </summary>
        public static string Inform_DeleteConnection {
            get {
                return ResourceManager.GetString("Inform_DeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin lỗi đã được xóa khỏi hệ thống !.
        /// </summary>
        public static string Inform_DeleteError {
            get {
                return ResourceManager.GetString("Inform_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giá trị định mức đã được xóa khỏi hệ thống !.
        /// </summary>
        public static string Inform_DeleteNorm {
            get {
                return ResourceManager.GetString("Inform_DeleteNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thay đổi trạng thái qui định kết nối !.
        /// </summary>
        public static string Inform_UpdateConnection {
            get {
                return ResourceManager.GetString("Inform_UpdateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thay đổi trạng thái lỗi !.
        /// </summary>
        public static string Inform_UpdateError {
            get {
                return ResourceManager.GetString("Inform_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thay đổi trạng thái giá trị định mức !.
        /// </summary>
        public static string Inform_UpdateNorm {
            get {
                return ResourceManager.GetString("Inform_UpdateNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mã định mức.
        /// </summary>
        public static string Norm_Code_Detail {
            get {
                return ResourceManager.GetString("Norm_Code_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định mức.
        /// </summary>
        public static string Norm_Code_List {
            get {
                return ResourceManager.GetString("Norm_Code_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định mức hàng hóa.
        /// </summary>
        public static string Norm_ListItem {
            get {
                return ResourceManager.GetString("Norm_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tê_n định mức.
        /// </summary>
        public static string Norm_Name_Detail {
            get {
                return ResourceManager.GetString("Norm_Name_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên định mức.
        /// </summary>
        public static string Norm_Name_List {
            get {
                return ResourceManager.GetString("Norm_Name_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ghi chú.
        /// </summary>
        public static string Norm_Note_Detail {
            get {
                return ResourceManager.GetString("Norm_Note_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Norm_Note_List {
            get {
                return ResourceManager.GetString("Norm_Note_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L_oại sản phảm.
        /// </summary>
        public static string Norm_ProductType_Detail {
            get {
                return ResourceManager.GetString("Norm_ProductType_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        public static string Norm_ProductType_List {
            get {
                return ResourceManager.GetString("Norm_ProductType_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T_rạng thái.
        /// </summary>
        public static string Norm_State_Detail {
            get {
                return ResourceManager.GetString("Norm_State_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Norm_State_List {
            get {
                return ResourceManager.GetString("Norm_State_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G_iá trị định mức.
        /// </summary>
        public static string Norm_Value_Detail {
            get {
                return ResourceManager.GetString("Norm_Value_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị định mức.
        /// </summary>
        public static string Norm_Value_List {
            get {
                return ResourceManager.GetString("Norm_Value_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
