//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _D.
        /// </summary>
        public static string Accesskey_D {
            get {
                return ResourceManager.GetString("Accesskey_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th_oát.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấ_u hình.
        /// </summary>
        public static string btnLoginConfig {
            get {
                return ResourceManager.GetString("btnLoginConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string Config_Title {
            get {
                return ResourceManager.GetString("Config_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn thoát khỏi chương trình không ?.
        /// </summary>
        public static string ConfirmShutdown {
            get {
                return ResourceManager.GetString("ConfirmShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string ConfirmShutdown_Caption {
            get {
                return ResourceManager.GetString("ConfirmShutdown_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái kết nối.
        /// </summary>
        public static string ConnectionStatus {
            get {
                return ResourceManager.GetString("ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MM-yyyy HH:mm:ss.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái thiết bị.
        /// </summary>
        public static string DeviceEffect_Title {
            get {
                return ResourceManager.GetString("DeviceEffect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hiệu lực thiết bị.
        /// </summary>
        public static string DeviceManagement_Title {
            get {
                return ResourceManager.GetString("DeviceManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thông tin giao dịch thiết bị.
        /// </summary>
        public static string DeviceManagementTransaction_title {
            get {
                return ResourceManager.GetString("DeviceManagementTransaction_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái thiết bị.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thông tin giao dịch thiết bị.
        /// </summary>
        public static string DeviceTrasaction_Title {
            get {
                return ResourceManager.GetString("DeviceTrasaction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang kiểm tra thông tin cấu hình và kết nối CSDL ....
        /// </summary>
        public static string Flash_RetriveConfigInfo {
            get {
                return ResourceManager.GetString("Flash_RetriveConfigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÂN HỆ GIÁM SÁT HẬU KIỂM.
        /// </summary>
        public static string Flash_Title {
            get {
                return ResourceManager.GetString("Flash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xem báo cáo hay quyền xem báo cáo của bạn đã bị hủy cho chức năng {0}. Xin vui lòng liên hệ quản trị viên !.
        /// </summary>
        public static string InfomationNotSecurityShowViewReport {
            get {
                return ResourceManager.GetString("InfomationNotSecurityShowViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không trùng với mật khẩu mới !.
        /// </summary>
        public static string Login_ConfirmPasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_ConfirmPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không đúng !.
        /// </summary>
        public static string Login_CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Thoát.
        /// </summary>
        public static string Login_Exit {
            get {
                return ResourceManager.GetString("Login_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Đăng nhập.
        /// </summary>
        public static string Login_OK {
            get {
                return ResourceManager.GetString("Login_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mật khẩu.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ca.
        /// </summary>
        public static string Login_Shift {
            get {
                return ResourceManager.GetString("Login_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Người dùng.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng hay mật khẩu không đúng !.
        /// </summary>
        public static string Login_UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_UsernamePasswordIncorrect_Caption {
            get {
                return ResourceManager.GetString("Login_UsernamePasswordIncorrect_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string menuChangePassword {
            get {
                return ResourceManager.GetString("menuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string menuLogin {
            get {
                return ResourceManager.GetString("menuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string menuLogout {
            get {
                return ResourceManager.GetString("menuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Giám sát                       .
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám sát.
        /// </summary>
        public static string Monitor_Header {
            get {
                return ResourceManager.GetString("Monitor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu admin không đúng\nVui lòng nhập lại mật khẩu !.
        /// </summary>
        public static string msgAdminPasswordIncorrect {
            get {
                return ResourceManager.GetString("msgAdminPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cấu hình !.
        /// </summary>
        public static string NotConfig {
            get {
                return ResourceManager.GetString("NotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm.
        /// </summary>
        public static string Postcheck_Header {
            get {
                return ResourceManager.GetString("Postcheck_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm vé lượt.
        /// </summary>
        public static string PostCheckCounter {
            get {
                return ResourceManager.GetString("PostCheckCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm vé lượt trừ dần.
        /// </summary>
        public static string PostCheckCounterDecuted {
            get {
                return ResourceManager.GetString("PostCheckCounterDecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm các lượt xe qua làn.
        /// </summary>
        public static string PostCheckCounterLane {
            get {
                return ResourceManager.GetString("PostCheckCounterLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm các lượt xe qua làn.
        /// </summary>
        public static string PostCheckCountTurnVehicleOverLane {
            get {
                return ResourceManager.GetString("PostCheckCountTurnVehicleOverLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe ưu tiên.
        /// </summary>
        public static string PostCheckIsforce {
            get {
                return ResourceManager.GetString("PostCheckIsforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm vé có thời hạn.
        /// </summary>
        public static string PostCheckPeriod {
            get {
                return ResourceManager.GetString("PostCheckPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe giao dịch bằng thẻ lượt.
        /// </summary>
        public static string RPT_ListVehicle {
            get {
                return ResourceManager.GetString("RPT_ListVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết hậu kiểm xe giao dịch bằng thẻ lượt.
        /// </summary>
        public static string RPT_ListVehicleDetail {
            get {
                return ResourceManager.GetString("RPT_ListVehicleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê kết quả hậu kiểm.
        /// </summary>
        public static string RPT_PostcheckResult {
            get {
                return ResourceManager.GetString("RPT_PostcheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số lượng hàng hóa.
        /// </summary>
        public static string RPT_ProdQuantity {
            get {
                return ResourceManager.GetString("RPT_ProdQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số lượng hàng hóa lưu hành.
        /// </summary>
        public static string RPT_ProdQuantityActive {
            get {
                return ResourceManager.GetString("RPT_ProdQuantityActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số lượng hàng hóa.
        /// </summary>
        public static string RPT_ProdQuantityExist {
            get {
                return ResourceManager.GetString("RPT_ProdQuantityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê doanh thu.
        /// </summary>
        public static string RPT_Revenue {
            get {
                return ResourceManager.GetString("RPT_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê theo lộ trình.
        /// </summary>
        public static string RPT_Route {
            get {
                return ResourceManager.GetString("RPT_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lưu lượng xe qua làn.
        /// </summary>
        public static string RPT_Traffic {
            get {
                return ResourceManager.GetString("RPT_Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn.
        /// </summary>
        public static string RPT_Turn {
            get {
                return ResourceManager.GetString("RPT_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm.
        /// </summary>
        public static string RPTPostCheck {
            get {
                return ResourceManager.GetString("RPTPostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên: {0} .
        /// </summary>
        public static string Status_Employee {
            get {
                return ResourceManager.GetString("Status_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám sát.
        /// </summary>
        public static string Supervision_Title {
            get {
                return ResourceManager.GetString("Supervision_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê doanh thu dạng biểu đồ.
        /// </summary>
        public static string SupervisionRevenueReportChart {
            get {
                return ResourceManager.GetString("SupervisionRevenueReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê doanh thu dạng bảng.
        /// </summary>
        public static string SupervisionRevenueReportTable {
            get {
                return ResourceManager.GetString("SupervisionRevenueReportTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lưu lượng xe qua làn dạng biểu đồ.
        /// </summary>
        public static string SupervisionTrafficReportChart {
            get {
                return ResourceManager.GetString("SupervisionTrafficReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lưu lượng xe qua làn dạng bảng.
        /// </summary>
        public static string SupervisionTrafficReportTable {
            get {
                return ResourceManager.GetString("SupervisionTrafficReportTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÂN HỆ GIÁM SÁT HẬU KIỂM - Version: 3.1.1.20170410.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cơ sở dữ liệu chuẩn.
        /// </summary>
        public static string Title_UpdateManagement {
            get {
                return ResourceManager.GetString("Title_UpdateManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cơ sở dữ liệu đăng kiểm.
        /// </summary>
        public static string Title_UpdateSatand {
            get {
                return ResourceManager.GetString("Title_UpdateSatand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý phương tiện.
        /// </summary>
        public static string Vehicle_Title {
            get {
                return ResourceManager.GetString("Vehicle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Quản lý     phương tiện .
        /// </summary>
        public static string VehicleManagement {
            get {
                return ResourceManager.GetString("VehicleManagement", resourceCulture);
            }
        }
    }
}
