//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostcheckReportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostcheckReportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.PostcheckReportStrings", typeof(PostcheckReportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nâng cao.
        /// </summary>
        public static string AdvanceFind {
            get {
                return ResourceManager.GetString("AdvanceFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các ngày ca.
        /// </summary>
        public static string AllShiftString {
            get {
                return ResourceManager.GetString("AllShiftString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các trạm.
        /// </summary>
        public static string AllStationString {
            get {
                return ResourceManager.GetString("AllStationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string AllString {
            get {
                return ResourceManager.GetString("AllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Tất cả&quot;, &quot;Hợp lệ&quot;, &quot;Không hợp lệ&quot;,&quot;Đang xem xét&quot;.
        /// </summary>
        public static string Array {
            get {
                return ResourceManager.GetString("Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Tất cả&quot;, &quot;Vé lượt&quot;, &quot;Vé thời gian&quot;, &quot;OBU 1 mảnh&quot;,&quot;OBU thời gian&quot; ,&quot;OBU 2 mảnh&quot;, &quot;SmartCard&quot;, &quot;SmartCard thời gian&quot;, &quot;Ưu tiên 1 xe&quot;, &quot;Ưu tiên đoàn xe&quot;, &quot;Bộ tài chính&quot;.
        /// </summary>
        public static string ArrayReviewString {
            get {
                return ResourceManager.GetString("ArrayReviewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ tài chính.
        /// </summary>
        public static string Btc {
            get {
                return ResourceManager.GetString("Btc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ.
        /// </summary>
        public static string CheckDate {
            get {
                return ResourceManager.GetString("CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string CodeDevide {
            get {
                return ResourceManager.GetString("CodeDevide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string CodeObjectString {
            get {
                return ResourceManager.GetString("CodeObjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ ưu tiên.
        /// </summary>
        public static string CodeTagIsForce {
            get {
                return ResourceManager.GetString("CodeTagIsForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vé.
        /// </summary>
        public static string Codevehilce {
            get {
                return ResourceManager.GetString("Codevehilce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe ND.
        /// </summary>
        public static string CogRegisNumber {
            get {
                return ResourceManager.GetString("CogRegisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string CogregisString {
            get {
                return ResourceManager.GetString("CogregisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện thống kê.
        /// </summary>
        public static string ConditionReport {
            get {
                return ResourceManager.GetString("ConditionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm soát.
        /// </summary>
        public static string ControlString {
            get {
                return ResourceManager.GetString("ControlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé lượt.
        /// </summary>
        public static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé thời gian.
        /// </summary>
        public static string CountTime {
            get {
                return ResourceManager.GetString("CountTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé tháng.
        /// </summary>
        public static string CountTimeMonth {
            get {
                return ResourceManager.GetString("CountTimeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé quí.
        /// </summary>
        public static string CountTimeQuarter {
            get {
                return ResourceManager.GetString("CountTimeQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ đóng.
        /// </summary>
        public static string DateClose {
            get {
                return ResourceManager.GetString("DateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ kiểm soát.
        /// </summary>
        public static string DateControlString {
            get {
                return ResourceManager.GetString("DateControlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiệu lực.
        /// </summary>
        public static string DateEffective {
            get {
                return ResourceManager.GetString("DateEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string DateExprired {
            get {
                return ResourceManager.GetString("DateExprired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn từ.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ.
        /// </summary>
        public static string DateHour {
            get {
                return ResourceManager.GetString("DateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ mở.
        /// </summary>
        public static string DateOPen {
            get {
                return ResourceManager.GetString("DateOPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string DateString {
            get {
                return ResourceManager.GetString("DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn đến.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string DayString {
            get {
                return ResourceManager.GetString("DayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartCard trừ dần.
        /// </summary>
        public static string DecutedSmartCard {
            get {
                return ResourceManager.GetString("DecutedSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày định dạng sai. Vui lòng kiểm tra lại !.
        /// </summary>
        public static string DefaultValidDateTime {
            get {
                return ResourceManager.GetString("DefaultValidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU, Smartcard.
        /// </summary>
        public static string Device_ListItem {
            get {
                return ResourceManager.GetString("Device_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm soát viên.
        /// </summary>
        public static string EmployeeControl {
            get {
                return ResourceManager.GetString("EmployeeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên hậu kiểm.
        /// </summary>
        public static string EmployeePostCheck {
            get {
                return ResourceManager.GetString("EmployeePostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string EmployeeString {
            get {
                return ResourceManager.GetString("EmployeeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thao tác chuyển form được.
        /// </summary>
        public static string ErrorNotChangeForm {
            get {
                return ResourceManager.GetString("ErrorNotChangeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng form không thao tác được.
        /// </summary>
        public static string ErrorNotClose {
            get {
                return ResourceManager.GetString("ErrorNotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thao tác được.
        /// </summary>
        public static string ErrorNotDelete {
            get {
                return ResourceManager.GetString("ErrorNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất ra Excel bị lỗi.
        /// </summary>
        public static string ErrorNotExcel {
            get {
                return ResourceManager.GetString("ErrorNotExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được dữ liệu lên các control.
        /// </summary>
        public static string ErrorNotLoadData {
            get {
                return ResourceManager.GetString("ErrorNotLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được giá vé lên combobox.
        /// </summary>
        public static string ErrorNotLoadDataTicket {
            get {
                return ResourceManager.GetString("ErrorNotLoadDataTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được loại phương tiện lên combobox.
        /// </summary>
        public static string ErrorNotLoadDataVehicle {
            get {
                return ResourceManager.GetString("ErrorNotLoadDataVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thao tác được hàm tìm kiếm.
        /// </summary>
        public static string ErrorNotLoadShowSearch {
            get {
                return ResourceManager.GetString("ErrorNotLoadShowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In báo cáo bị lỗi.
        /// </summary>
        public static string ErrorNotPrint {
            get {
                return ResourceManager.GetString("ErrorNotPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý dữ liệu bị lỗi.
        /// </summary>
        public static string ErrorNotProcess {
            get {
                return ResourceManager.GetString("ErrorNotProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thao tác được bất đồng bộ.
        /// </summary>
        public static string ErrorNotProgessbar {
            get {
                return ResourceManager.GetString("ErrorNotProgessbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất báo cáo bị lỗi.
        /// </summary>
        public static string ErrorNotReport {
            get {
                return ResourceManager.GetString("ErrorNotReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu dữ liệu không thành công.
        /// </summary>
        public static string ErrorNotSaveData {
            get {
                return ResourceManager.GetString("ErrorNotSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không gán được giá trị cho biến.
        /// </summary>
        public static string ErrorNotSession {
            get {
                return ResourceManager.GetString("ErrorNotSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cập nhật dữ liệu. Hãy kiểm tra kết nối..
        /// </summary>
        public static string ErrorUpdateData {
            get {
                return ResourceManager.GetString("ErrorUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã in hoàn tất.
        /// </summary>
        public static string FinishReportPrint {
            get {
                return ResourceManager.GetString("FinishReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string FromDay {
            get {
                return ResourceManager.GetString("FromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƯT đoàn xe.
        /// </summary>
        public static string GroupIsforce {
            get {
                return ResourceManager.GetString("GroupIsforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu phải nhỏ hơn giờ kết thúc !.
        /// </summary>
        public static string HourelessThanHourEnd {
            get {
                return ResourceManager.GetString("HourelessThanHourEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thu.
        /// </summary>
        public static string ImportMoney {
            get {
                return ResourceManager.GetString("ImportMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƯT1X CT.
        /// </summary>
        public static string Isforce {
            get {
                return ResourceManager.GetString("Isforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƯT1X KT.
        /// </summary>
        public static string IsForceNoCard {
            get {
                return ResourceManager.GetString("IsForceNoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe quay đầu.
        /// </summary>
        public static string IsForceTurnBack {
            get {
                return ResourceManager.GetString("IsForceTurnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hậu kiểm.
        /// </summary>
        public static string IsPostCheckString {
            get {
                return ResourceManager.GetString("IsPostCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn.
        /// </summary>
        public static string LaneString {
            get {
                return ResourceManager.GetString("LaneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền còn lại.
        /// </summary>
        public static string MoneyBalance {
            get {
                return ResourceManager.GetString("MoneyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền trừ.
        /// </summary>
        public static string Moneydevide {
            get {
                return ResourceManager.GetString("Moneydevide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa tiền kiểm.
        /// </summary>
        public static string NotCheckString {
            get {
                return ResourceManager.GetString("NotCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu cho điều kiện thống kê bạn chọn !.
        /// </summary>
        public static string NotData {
            get {
                return ResourceManager.GetString("NotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để in báo cáo !.
        /// </summary>
        public static string NotDataPrintReport {
            get {
                return ResourceManager.GetString("NotDataPrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa hậu kiểm.
        /// </summary>
        public static string NotPostCheckString {
            get {
                return ResourceManager.GetString("NotPostCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác định.
        /// </summary>
        public static string NotReviewString {
            get {
                return ResourceManager.GetString("NotReviewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ.
        /// </summary>
        public static string Notvalid {
            get {
                return ResourceManager.GetString("Notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        public static string ObjectString {
            get {
                return ResourceManager.GetString("ObjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU 1 mảnh.
        /// </summary>
        public static string OBU1 {
            get {
                return ResourceManager.GetString("OBU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU 2 mảnh.
        /// </summary>
        public static string OBU2 {
            get {
                return ResourceManager.GetString("OBU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obu tháng.
        /// </summary>
        public static string ObuMonth {
            get {
                return ResourceManager.GetString("ObuMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obu quí.
        /// </summary>
        public static string ObuQuarter {
            get {
                return ResourceManager.GetString("ObuQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU thời gian.
        /// </summary>
        public static string OBUTime {
            get {
                return ResourceManager.GetString("OBUTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem xét.
        /// </summary>
        public static string Others_ListItem {
            get {
                return ResourceManager.GetString("Others_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé tháng, quí.
        /// </summary>
        public static string Period_ListItem {
            get {
                return ResourceManager.GetString("Period_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png.
        /// </summary>
        public static string PostCheckCounterDetailViewModel_PostCheckCounterDetailViewModel_PNG_File___png {
            get {
                return ResourceManager.GetString("PostCheckCounterDetailViewModel_PostCheckCounterDetailViewModel_PNG_File___png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png.
        /// </summary>
        public static string PostCheckDetailIsForceViewModel_PostCheckDetailIsForceViewModel_PNG_File___png {
            get {
                return ResourceManager.GetString("PostCheckDetailIsForceViewModel_PostCheckDetailIsForceViewModel_PNG_File___png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hậu kiểm không hợp lệ.
        /// </summary>
        public static string PostCheckNotValidString {
            get {
                return ResourceManager.GetString("PostCheckNotValidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png.
        /// </summary>
        public static string PostcheckResultDetailViewModel_PostcheckResultDetailViewModel_PNG_File___png {
            get {
                return ResourceManager.GetString("PostcheckResultDetailViewModel_PostcheckResultDetailViewModel_PNG_File___png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm.
        /// </summary>
        public static string PostCheckString {
            get {
                return ResourceManager.GetString("PostCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hậu kiểm hợp lệ.
        /// </summary>
        public static string PostCheckValidString {
            get {
                return ResourceManager.GetString("PostCheckValidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá vé.
        /// </summary>
        public static string PriceString {
            get {
                return ResourceManager.GetString("PriceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _In báo cáo.
        /// </summary>
        public static string PrintReportString {
            get {
                return ResourceManager.GetString("PrintReportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên.
        /// </summary>
        public static string Priority_ListItem {
            get {
                return ResourceManager.GetString("Priority_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe đăng ký.
        /// </summary>
        public static string RegisPlateNumber {
            get {
                return ResourceManager.GetString("RegisPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string RegisplateString {
            get {
                return ResourceManager.GetString("RegisplateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất _Excel.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê kết quả nhân viên hậu kiểm.
        /// </summary>
        public static string ReportEmployeeString {
            get {
                return ResourceManager.GetString("ReportEmployeeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn : hậu kiểm vé lượt.
        /// </summary>
        public static string ReportErrorFormPostCheckCounter {
            get {
                return ResourceManager.GetString("ReportErrorFormPostCheckCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn : Hậu kiểm vé lượt trừ dần.
        /// </summary>
        public static string ReportErrorFormPostCheckCounterDecuted {
            get {
                return ResourceManager.GetString("ReportErrorFormPostCheckCounterDecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn : Hậu kiểm các lượt xe qua làn.
        /// </summary>
        public static string ReportErrorFormPostCheckCounterVehicle {
            get {
                return ResourceManager.GetString("ReportErrorFormPostCheckCounterVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn: Hậu kiểm xe ưu tiên.
        /// </summary>
        public static string ReportErrorFormPostCheckIsforce {
            get {
                return ResourceManager.GetString("ReportErrorFormPostCheckIsforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn : Hậu kiểm vé thời gian.
        /// </summary>
        public static string ReportErrorFormPostCheckPeriod {
            get {
                return ResourceManager.GetString("ReportErrorFormPostCheckPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cơ sở dữ liệu đăng kiểm.
        /// </summary>
        public static string ReportErrorFormVehicleInformation {
            get {
                return ResourceManager.GetString("ReportErrorFormVehicleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm phương tiện.
        /// </summary>
        public static string ReportErrorFormVehicleInformationFind {
            get {
                return ResourceManager.GetString("ReportErrorFormVehicleInformationFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cơ sở dữ liệu chuẩn.
        /// </summary>
        public static string ReportErrorFormVehicleInformationManual {
            get {
                return ResourceManager.GetString("ReportErrorFormVehicleInformationManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê kết quả hậu kiểm .
        /// </summary>
        public static string ReportPostCheck {
            get {
                return ResourceManager.GetString("ReportPostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn - hậu kiểm vé lượt trừ dần.
        /// </summary>
        public static string ReportTitlePostCheckCounterDecuted {
            get {
                return ResourceManager.GetString("ReportTitlePostCheckCounterDecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn - hậu kiểm vé có thời hạn.
        /// </summary>
        public static string ReportTitlePostCheckCounterPeriod {
            get {
                return ResourceManager.GetString("ReportTitlePostCheckCounterPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn - hậu kiểm các lượt xe qua làn.
        /// </summary>
        public static string ReportTitlePostCheckCounteVehicle {
            get {
                return ResourceManager.GetString("ReportTitlePostCheckCounteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn - hậu kiểm xe ưu tiên.
        /// </summary>
        public static string ReportTitlePostCheckResultIsForce {
            get {
                return ResourceManager.GetString("ReportTitlePostCheckResultIsForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê các lượt xe qua làn - hậu kiểm vé lượt.
        /// </summary>
        public static string ReportTitlePostCheckTurnTickket {
            get {
                return ResourceManager.GetString("ReportTitlePostCheckTurnTickket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KQ nhân viên hậu kiểm.
        /// </summary>
        public static string ResultPostString {
            get {
                return ResourceManager.GetString("ResultPostString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KQ hệ thống hậu kiểm.
        /// </summary>
        public static string ResultSysPostString {
            get {
                return ResourceManager.GetString("ResultSysPostString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xem xét.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KQ hậu kiểm.
        /// </summary>
        public static string ReviewString {
            get {
                return ResourceManager.GetString("ReviewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình.
        /// </summary>
        public static string RouteName {
            get {
                return ResourceManager.GetString("RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn card hoặc vé để thống kê !.
        /// </summary>
        public static string SelectCardorCountReport {
            get {
                return ResourceManager.GetString("SelectCardorCountReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn vé giấy, OBU hoặc SmartCard để thống kê !.
        /// </summary>
        public static string SelectCountOBUSmartCardReport {
            get {
                return ResourceManager.GetString("SelectCountOBUSmartCardReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn 1 lượt, tháng quí, trừ dần hoặc ưu tiên để thống kê !.
        /// </summary>
        public static string SelectCountPeriodDecutedIsforceReport {
            get {
                return ResourceManager.GetString("SelectCountPeriodDecutedIsforceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ưu tiên 1 xe, ưu tiên đoàn xe để thống kê !.
        /// </summary>
        public static string SelectIsforceGroupIsforceReport {
            get {
                return ResourceManager.GetString("SelectIsforceGroupIsforceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn OBU 1 mảnh, OBU 2 mảnh hoặc SmartCard để thống kê !.
        /// </summary>
        public static string SelectOBu1OBU2SmartCardReport {
            get {
                return ResourceManager.GetString("SelectOBu1OBU2SmartCardReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ca.
        /// </summary>
        public static string ShiftDay {
            get {
                return ResourceManager.GetString("ShiftDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string ShiftString {
            get {
                return ResourceManager.GetString("ShiftString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ.
        /// </summary>
        public static string SmartCard {
            get {
                return ResourceManager.GetString("SmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ tháng.
        /// </summary>
        public static string SmartCardMonth {
            get {
                return ResourceManager.GetString("SmartCardMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ quí.
        /// </summary>
        public static string SmartCardQuarter {
            get {
                return ResourceManager.GetString("SmartCardQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ thời gian.
        /// </summary>
        public static string SmartCardTime {
            get {
                return ResourceManager.GetString("SmartCardTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm.
        /// </summary>
        public static string StationString {
            get {
                return ResourceManager.GetString("StationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống hậu kiểm.
        /// </summary>
        public static string SysPostCheck {
            get {
                return ResourceManager.GetString("SysPostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại vé.
        /// </summary>
        public static string TicketType {
            get {
                return ResourceManager.GetString("TicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vé.
        /// </summary>
        public static string TickketCode {
            get {
                return ResourceManager.GetString("TickketCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê kết quả hậu kiểm.
        /// </summary>
        public static string TitilePostCheck {
            get {
                return ResourceManager.GetString("TitilePostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp.
        /// </summary>
        public static string Total_ListItem {
            get {
                return ResourceManager.GetString("Total_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi thống kê: (SupervisionTrafficReportViewModel)(this.DataContext) == null.
        /// </summary>
        public static string TrafficNotError {
            get {
                return ResourceManager.GetString("TrafficNotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé lượt.
        /// </summary>
        public static string Turn_ListItem {
            get {
                return ResourceManager.GetString("Turn_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượt.
        /// </summary>
        public static string TurnCount {
            get {
                return ResourceManager.GetString("TurnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại kiểm soát.
        /// </summary>
        public static string TypeControl {
            get {
                return ResourceManager.GetString("TypeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thiết bị.
        /// </summary>
        public static string TypeDevide {
            get {
                return ResourceManager.GetString("TypeDevide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng lưới.
        /// </summary>
        public static string TypeGridString {
            get {
                return ResourceManager.GetString("TypeGridString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại ưu tiên.
        /// </summary>
        public static string TypeIsForce {
            get {
                return ResourceManager.GetString("TypeIsForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem báo cáo.
        /// </summary>
        public static string TypeReportString {
            get {
                return ResourceManager.GetString("TypeReportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string TypeVehicle {
            get {
                return ResourceManager.GetString("TypeVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xem báo cáo.
        /// </summary>
        public static string WatchReportString {
            get {
                return ResourceManager.GetString("WatchReportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn load lại dữ liệu không ?.
        /// </summary>
        public static string YesNoQuestion_Load {
            get {
                return ResourceManager.GetString("YesNoQuestion_Load", resourceCulture);
            }
        }
    }
}
