//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoutedReportsString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoutedReportsString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.RoutedReportsString", typeof(RoutedReportsString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string AllTypeVehicle {
            get {
                return ResourceManager.GetString("AllTypeVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số  HĐ.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí thu.
        /// </summary>
        public static string Chargamount {
            get {
                return ResourceManager.GetString("Chargamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -No.
        /// </summary>
        public static string CodeDevideWhenNull {
            get {
                return ResourceManager.GetString("CodeDevideWhenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        public static string CodeSmartCard {
            get {
                return ResourceManager.GetString("CodeSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung lỗi: {0}.
        /// </summary>
        public static string ContentError {
            get {
                return ResourceManager.GetString("ContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày .
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ vào.
        /// </summary>
        public static string DateIn {
            get {
                return ResourceManager.GetString("DateIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ ra.
        /// </summary>
        public static string DateOut {
            get {
                return ResourceManager.GetString("DateOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lúc {0}.
        /// </summary>
        public static string DateStatistics {
            get {
                return ResourceManager.GetString("DateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác loại.
        /// </summary>
        public static string DiffTypeVehicle {
            get {
                return ResourceManager.GetString("DiffTypeVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng cách.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên thu tiền.
        /// </summary>
        public static string Employee_Money {
            get {
                return ResourceManager.GetString("Employee_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel(.Excel)|*.xls.
        /// </summary>
        public static string Export_Excel_Filter {
            get {
                return ResourceManager.GetString("Export_Excel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu  báo cáo thống kê các phương tiện cổng vào ra.
        /// </summary>
        public static string Export_Excel_Title {
            get {
                return ResourceManager.GetString("Export_Excel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo thống kê lộ trình.
        /// </summary>
        public static string Export_Excel_Tittle {
            get {
                return ResourceManager.GetString("Export_Excel_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo thống kê kết quả hậu kiểm.
        /// </summary>
        public static string ExportExcelTitlePostCheck {
            get {
                return ResourceManager.GetString("ExportExcelTitlePostCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo hậu kiểm vé lượt trừ dần.
        /// </summary>
        public static string ExportExcelTitlePostCheckCounterDecuted {
            get {
                return ResourceManager.GetString("ExportExcelTitlePostCheckCounterDecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo hậu kiểm vé có thời hạn.
        /// </summary>
        public static string ExportExcelTitlePostCheckCounterPeriod {
            get {
                return ResourceManager.GetString("ExportExcelTitlePostCheckCounterPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo hậu kiểm các lượt xe qua làn.
        /// </summary>
        public static string ExportExcelTitlePostCheckCounterVehicle {
            get {
                return ResourceManager.GetString("ExportExcelTitlePostCheckCounterVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo hậu kiểm xe ưu tiên.
        /// </summary>
        public static string ExportExcelTitlePostCheckIsForce {
            get {
                return ResourceManager.GetString("ExportExcelTitlePostCheckIsForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu báo cáo hậu kiểm vé lượt.
        /// </summary>
        public static string ExportExcelTitlePostCheckTurnCounter {
            get {
                return ResourceManager.GetString("ExportExcelTitlePostCheckTurnCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm giao dịch thẻ trả trước.
        /// </summary>
        public static string FileNamePostCheckPrepaidCard {
            get {
                return ResourceManager.GetString("FileNamePostCheckPrepaidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe giao dịch bằng thẻ.
        /// </summary>
        public static string FileNamePostCheckSmartCard {
            get {
                return ResourceManager.GetString("FileNamePostCheckSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giao dịch thẻ trả trước.
        /// </summary>
        public static string FileNamePrepaidCardList {
            get {
                return ResourceManager.GetString("FileNamePrepaidCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lộ trình.
        /// </summary>
        public static string FileNameRoute {
            get {
                return ResourceManager.GetString("FileNameRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại tập tin này đang mở không thể lưu tập tin này !.
        /// </summary>
        public static string FileOpeningNotSave {
            get {
                return ResourceManager.GetString("FileOpeningNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã in hoàn tất !.
        /// </summary>
        public static string FinishReportPrint {
            get {
                return ResourceManager.GetString("FinishReportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng: {0}.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải nhỏ hơn ngày kết thúc !.
        /// </summary>
        public static string FromDateLessThanToDate {
            get {
                return ResourceManager.GetString("FromDateLessThanToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian từ ngày không được để trống !.
        /// </summary>
        public static string FromDateTimeNotNull {
            get {
                return ResourceManager.GetString("FromDateTimeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu phải nhỏ hơn giờ kết thúc !.
        /// </summary>
        public static string FromTimeLessThanToTime {
            get {
                return ResourceManager.GetString("FromTimeLessThanToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian từ giờ không được để trống !.
        /// </summary>
        public static string FromTimeNotNull {
            get {
                return ResourceManager.GetString("FromTimeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàm: {0}.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng vào.
        /// </summary>
        public static string GateIn {
            get {
                return ResourceManager.GetString("GateIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng ra.
        /// </summary>
        public static string GateOut {
            get {
                return ResourceManager.GetString("GateOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin soát vé.
        /// </summary>
        public static string GroupInInfor {
            get {
                return ResourceManager.GetString("GroupInInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin soát vé.
        /// </summary>
        public static string GroupOutInfor {
            get {
                return ResourceManager.GetString("GroupOutInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ giờ .
        /// </summary>
        public static string HourFrom {
            get {
                return ResourceManager.GetString("HourFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến giờ.
        /// </summary>
        public static string HourTo {
            get {
                return ResourceManager.GetString("HourTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ vào - Ngày giờ ra.
        /// </summary>
        public static string In_Out_Date {
            get {
                return ResourceManager.GetString("In_Out_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn lưu chấm lỗi này?.
        /// </summary>
        public static string InfomationAcceptSaveSupevision {
            get {
                return ResourceManager.GetString("InfomationAcceptSaveSupevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thống kê hay quyền thống kê trên chức năng này đã bị hủy. Vui lòng liên hệ quản trị viên!.
        /// </summary>
        public static string InfoNotSupervision {
            get {
                return ResourceManager.GetString("InfoNotSupervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ Làn.
        /// </summary>
        public static string LaneFrom {
            get {
                return ResourceManager.GetString("LaneFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn vào.
        /// </summary>
        public static string LaneIn {
            get {
                return ResourceManager.GetString("LaneIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn ra.
        /// </summary>
        public static string LaneOut {
            get {
                return ResourceManager.GetString("LaneOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến làn.
        /// </summary>
        public static string LaneTo {
            get {
                return ResourceManager.GetString("LaneTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        public static string LevelCost {
            get {
                return ResourceManager.GetString("LevelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm thống kê phải trước ngày hiện tại !.
        /// </summary>
        public static string Message_Error_Time_MustBeLessThan_Now {
            get {
                return ResourceManager.GetString("Message_Error_Time_MustBeLessThan_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thu.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trạm.
        /// </summary>
        public static string NameStation {
            get {
                return ResourceManager.GetString("NameStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In báo cáo có lỗi do không thể kết nối đến máy in {0} !.
        /// </summary>
        public static string NotAccessPrint {
            get {
                return ResourceManager.GetString("NotAccessPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy dữ liệu đưa lên lưới.
        /// </summary>
        public static string NotCanGetDataToGrid {
            get {
                return ResourceManager.GetString("NotCanGetDataToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy thông tin về công ty để hiện lên góc trái báo cáo.
        /// </summary>
        public static string NotCanGetInfoCompanyForReport {
            get {
                return ResourceManager.GetString("NotCanGetInfoCompanyForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy thông tin xe hiện tại.
        /// </summary>
        public static string NotCanGetInfoShiftCurrent {
            get {
                return ResourceManager.GetString("NotCanGetInfoShiftCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy các thông tin cần thiết để đưa lên giao diện chương trình..
        /// </summary>
        public static string NotCanGetInfoToDesignGrid {
            get {
                return ResourceManager.GetString("NotCanGetInfoToDesignGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy các thông tin từ CSDL để thể hiện lên biểu đồ.
        /// </summary>
        public static string NotCanGetInfoToShowChart {
            get {
                return ResourceManager.GetString("NotCanGetInfoToShowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy danh sách nhân viên.
        /// </summary>
        public static string NotCanGetListEmployee {
            get {
                return ResourceManager.GetString("NotCanGetListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy các thông tin về hậu kiểm xe giao dịch bằng thẻ để hiện lên báo cáo theo điều kiện tìm kiếm tương ứng.
        /// </summary>
        public static string NotCanGetListInfoForReport {
            get {
                return ResourceManager.GetString("NotCanGetListInfoForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy các thông tin về hậu kiểm xe giao dịch bằng thẻ để hiện lên giao dịch theo điều kiện tìm kiếm tương ứng..
        /// </summary>
        public static string NotCanGetListInfoForSearch {
            get {
                return ResourceManager.GetString("NotCanGetListInfoForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy danh sách các làn ra của trạm tương ứng được chọn.
        /// </summary>
        public static string NotCanGetListLaneOfStation {
            get {
                return ResourceManager.GetString("NotCanGetListLaneOfStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy danh sách các lộ trình.
        /// </summary>
        public static string NotCanGetListRoute {
            get {
                return ResourceManager.GetString("NotCanGetListRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy danh sách các ca trong ngày.
        /// </summary>
        public static string NotCanGetListShift {
            get {
                return ResourceManager.GetString("NotCanGetListShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy danh sách các trạm.
        /// </summary>
        public static string NotCanGetListStation {
            get {
                return ResourceManager.GetString("NotCanGetListStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy các thông tin đưa lên báo cáo.
        /// </summary>
        public static string NotCanGetListToReport {
            get {
                return ResourceManager.GetString("NotCanGetListToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy được tổng số dòng cho hậu kiểm xe giao dịch bằng thẻ theo điều kiện tìm kiếm tương ứng.
        /// </summary>
        public static string NotCanGetTotalRecordForPostCheckSmartCard {
            get {
                return ResourceManager.GetString("NotCanGetTotalRecordForPostCheckSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lưu chấm lỗi hậu kiểm xe giao dịch bằng thẻ.
        /// </summary>
        public static string NotCanSaveMarkError {
            get {
                return ResourceManager.GetString("NotCanSaveMarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cấu hình kiểu file hoặc folder hình nhận dạng !.
        /// </summary>
        public static string NotConfigFileTypeOrFolrderRecogImage {
            get {
                return ResourceManager.GetString("NotConfigFileTypeOrFolrderRecogImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cấu hình folder hình chuẩn !.
        /// </summary>
        public static string NotConfigFolderStandImage {
            get {
                return ResourceManager.GetString("NotConfigFolderStandImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối với CSDL.
        /// </summary>
        public static string NotConnectDB {
            get {
                return ResourceManager.GetString("NotConnectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối với CSDL !.
        /// </summary>
        public static string NotConnectToDatabaseServer {
            get {
                return ResourceManager.GetString("NotConnectToDatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi Chú.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm từ phải khác trạm đến !.
        /// </summary>
        public static string NotStationFrom_To {
            get {
                return ResourceManager.GetString("NotStationFrom_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm đến phải khác trạm từ !.
        /// </summary>
        public static string NotStationTo_From {
            get {
                return ResourceManager.GetString("NotStationTo_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể truyền các giá trị từ form hậu kiểm xe giao dịch bằng thẻ qua form chi tiết hậu kiểm xe giao dịch bằng thẻ nên không thể xem chi tiết..
        /// </summary>
        public static string NotTransactionFromMainToDetail {
            get {
                return ResourceManager.GetString("NotTransactionFromMainToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để xem chi tiết cho phần này !.
        /// </summary>
        public static string NotValueForViewDetail {
            get {
                return ResourceManager.GetString("NotValueForViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string ObjectCode {
            get {
                return ResourceManager.GetString("ObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ phương tiện.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn không tồn tại !.
        /// </summary>
        public static string PathNotExist {
            get {
                return ResourceManager.GetString("PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe giao dịch bằng thẻ chi tiết.
        /// </summary>
        public static string PostCheckSmartcardDetailForError {
            get {
                return ResourceManager.GetString("PostCheckSmartcardDetailForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe giao dịch bằng thẻ.
        /// </summary>
        public static string PostCheckSmartCardForError {
            get {
                return ResourceManager.GetString("PostCheckSmartCardForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư cuối.
        /// </summary>
        public static string PPC_Balance {
            get {
                return ResourceManager.GetString("PPC_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư đầu.
        /// </summary>
        public static string PPC_BeginBalance {
            get {
                return ResourceManager.GetString("PPC_BeginBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giao dịch.
        /// </summary>
        public static string PPC_SequenceID {
            get {
                return ResourceManager.GetString("PPC_SequenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG(*.png) |*.png|JPEG (*.jpeg,*.jpg)|*.jpg|GIF (*.gif)|*.gif|BMP (.bmp)|*.bmp.
        /// </summary>
        public static string PrintMonitorListVehicle_Filter {
            get {
                return ResourceManager.GetString("PrintMonitorListVehicle_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ảnh chụp màn hình.
        /// </summary>
        public static string PrintMonitorListVehicle_Tiltle {
            get {
                return ResourceManager.GetString("PrintMonitorListVehicle_Tiltle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LƯỢNG THẺ ĐANG SỬ DỤNG TẠI LÀN.
        /// </summary>
        public static string ProductQuantitySmartCard {
            get {
                return ResourceManager.GetString("ProductQuantitySmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string rd_All {
            get {
                return ResourceManager.GetString("rd_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình sai.
        /// </summary>
        public static string rd_RoutedFail {
            get {
                return ResourceManager.GetString("rd_RoutedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình đúng.
        /// </summary>
        public static string rd_RoutedTrust {
            get {
                return ResourceManager.GetString("rd_RoutedTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do: {0}.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe nhận dạng.
        /// </summary>
        public static string RecogPlateNumber {
            get {
                return ResourceManager.GetString("RecogPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -No.
        /// </summary>
        public static string RecogPlateNumberWhenNull {
            get {
                return ResourceManager.GetString("RecogPlateNumberWhenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng ký .
        /// </summary>
        public static string RegisDate {
            get {
                return ResourceManager.GetString("RegisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các ngày ca.
        /// </summary>
        public static string Report_Shift_All {
            get {
                return ResourceManager.GetString("Report_Shift_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách xe ưu tiên.
        /// </summary>
        public static string ReportPriorityVehicle {
            get {
                return ResourceManager.GetString("ReportPriorityVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe giao dịch bằng thẻ.
        /// </summary>
        public static string ReportTileVehicle {
            get {
                return ResourceManager.GetString("ReportTileVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hậu kiểm xe giao dịch bằng thẻ trả trước.
        /// </summary>
        public static string ReportTitleVehiclePrepaidCard {
            get {
                return ResourceManager.GetString("ReportTitleVehiclePrepaidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ LỘ TRÌNH.
        /// </summary>
        public static string Route_Title_Report {
            get {
                return ResourceManager.GetString("Route_Title_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỪ: {0} - ĐẾN: {1}.
        /// </summary>
        public static string Route_Title_Report_From_To {
            get {
                return ResourceManager.GetString("Route_Title_Report_From_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình.
        /// </summary>
        public static string Routed {
            get {
                return ResourceManager.GetString("Routed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cùng loại.
        /// </summary>
        public static string SameTypeVehicle {
            get {
                return ResourceManager.GetString("SameTypeVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chuẩn đã được lưu thành công !.
        /// </summary>
        public static string SaveImageStandSuccessful {
            get {
                return ResourceManager.GetString("SaveImageStandSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chỗ.
        /// </summary>
        public static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Ngày.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem _báo cáo.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ Trạm.
        /// </summary>
        public static string StationFrom {
            get {
                return ResourceManager.GetString("StationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến Trạm.
        /// </summary>
        public static string StationTo {
            get {
                return ResourceManager.GetString("StationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ừng.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng lượt: {0}.
        /// </summary>
        public static string SumPrice_Titiel {
            get {
                return ResourceManager.GetString("SumPrice_Titiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền bằng chữ: {0}.
        /// </summary>
        public static string SumPriceWord_Title {
            get {
                return ResourceManager.GetString("SumPriceWord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền: {0}.
        /// </summary>
        public static string SumTurn_Titiel {
            get {
                return ResourceManager.GetString("SumTurn_Titiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số lượng hàng hóa.
        /// </summary>
        public static string SupervisionProductQuantityForError {
            get {
                return ResourceManager.GetString("SupervisionProductQuantityForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lưu lượng xe qua làn dạng biểu đồ.
        /// </summary>
        public static string SupervisionTrafficVehicleLaneChart {
            get {
                return ResourceManager.GetString("SupervisionTrafficVehicleLaneChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cập nhật.
        /// </summary>
        public static string TimeUpdate {
            get {
                return ResourceManager.GetString("TimeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cập  nhật không được để trống!.
        /// </summary>
        public static string TimeUpdateNotEmpty {
            get {
                return ResourceManager.GetString("TimeUpdateNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cập  nhật không đúng định dạng!.
        /// </summary>
        public static string TimeUpdateNotFormat {
            get {
                return ResourceManager.GetString("TimeUpdateNotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê số lượng card đang sử dụng tại làn.
        /// </summary>
        public static string TititleProductCardActive {
            get {
                return ResourceManager.GetString("TititleProductCardActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đến ngày  không được để trống.
        /// </summary>
        public static string ToDateTimeNotNull {
            get {
                return ResourceManager.GetString("ToDateTimeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đến giờ không được để trống.
        /// </summary>
        public static string ToTimeNoNull {
            get {
                return ResourceManager.GetString("ToTimeNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string UI_2Cham {
            get {
                return ResourceManager.GetString("UI_2Cham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _o.
        /// </summary>
        public static string UI_AutoShortKey {
            get {
                return ResourceManager.GetString("UI_AutoShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _In chi tiết.
        /// </summary>
        public static string UI_bt_PrintDetail {
            get {
                return ResourceManager.GetString("UI_bt_PrintDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem _báo cáo.
        /// </summary>
        public static string UI_bt_ViewPrintReport {
            get {
                return ResourceManager.GetString("UI_bt_ViewPrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Đầu.
        /// </summary>
        public static string UI_btFirst {
            get {
                return ResourceManager.GetString("UI_btFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuối &gt;&gt;.
        /// </summary>
        public static string UI_btLast {
            get {
                return ResourceManager.GetString("UI_btLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau &gt;.
        /// </summary>
        public static string UI_btNext {
            get {
                return ResourceManager.GetString("UI_btNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Trước.
        /// </summary>
        public static string UI_btPre {
            get {
                return ResourceManager.GetString("UI_btPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th_oát.
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _o.
        /// </summary>
        public static string UI_Close_ShortKey {
            get {
                return ResourceManager.GetString("UI_Close_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện thống kê .
        /// </summary>
        public static string UI_Condition {
            get {
                return ResourceManager.GetString("UI_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        public static string UI_Cost {
            get {
                return ResourceManager.GetString("UI_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string UI_date {
            get {
                return ResourceManager.GetString("UI_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ vào - Ngày giờ ra.
        /// </summary>
        public static string UI_DateIn_DateOut {
            get {
                return ResourceManager.GetString("UI_DateIn_DateOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên KS.
        /// </summary>
        public static string UI_Employee {
            get {
                return ResourceManager.GetString("UI_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất _Excel.
        /// </summary>
        public static string UI_ExcelExport {
            get {
                return ResourceManager.GetString("UI_ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _E.
        /// </summary>
        public static string UI_ExeclExport_ShortKey {
            get {
                return ResourceManager.GetString("UI_ExeclExport_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng vào và cổng ra cùng đúng.
        /// </summary>
        public static string UI_GateInAndOutWright {
            get {
                return ResourceManager.GetString("UI_GateInAndOutWright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng vào và cổng ra cùng sai.
        /// </summary>
        public static string UI_GateInAndOutWrong {
            get {
                return ResourceManager.GetString("UI_GateInAndOutWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng vào sai.
        /// </summary>
        public static string UI_GateInWrong {
            get {
                return ResourceManager.GetString("UI_GateInWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng ra sai.
        /// </summary>
        public static string UI_GateOutWrong {
            get {
                return ResourceManager.GetString("UI_GateOutWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ.
        /// </summary>
        public static string UI_Hour {
            get {
                return ResourceManager.GetString("UI_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn.
        /// </summary>
        public static string UI_Lane {
            get {
                return ResourceManager.GetString("UI_Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string UI_ObjectCode {
            get {
                return ResourceManager.GetString("UI_ObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đối tượng.
        /// </summary>
        public static string UI_ObjectType {
            get {
                return ResourceManager.GetString("UI_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string UI_Parameter {
            get {
                return ResourceManager.GetString("UI_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _In màn hình.
        /// </summary>
        public static string UI_PrintMonitor {
            get {
                return ResourceManager.GetString("UI_PrintMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In màn hình.
        /// </summary>
        public static string UI_PrintScreen {
            get {
                return ResourceManager.GetString("UI_PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe nhận dạng.
        /// </summary>
        public static string UI_RecogPlateNumber {
            get {
                return ResourceManager.GetString("UI_RecogPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe ND.
        /// </summary>
        public static string UI_RecogPlateNumber1 {
            get {
                return ResourceManager.GetString("UI_RecogPlateNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe ND vào.
        /// </summary>
        public static string UI_RecogPlateNumberIn {
            get {
                return ResourceManager.GetString("UI_RecogPlateNumberIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe ND ra.
        /// </summary>
        public static string UI_RecogPlateNumberOut {
            get {
                return ResourceManager.GetString("UI_RecogPlateNumberOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe ĐK.
        /// </summary>
        public static string UI_RegisterPlateNumber {
            get {
                return ResourceManager.GetString("UI_RegisterPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá kết quả.
        /// </summary>
        public static string UI_Result {
            get {
                return ResourceManager.GetString("UI_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string UI_RouteDetailCount {
            get {
                return ResourceManager.GetString("UI_RouteDetailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin lộ trình.
        /// </summary>
        public static string UI_RouteInfor {
            get {
                return ResourceManager.GetString("UI_RouteInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình:.
        /// </summary>
        public static string UI_RouteName {
            get {
                return ResourceManager.GetString("UI_RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lưu hình chuẩn.
        /// </summary>
        public static string UI_SaveImageStatand {
            get {
                return ResourceManager.GetString("UI_SaveImageStatand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu hình chu_ẩn.
        /// </summary>
        public static string UI_SaveImageStatandOut {
            get {
                return ResourceManager.GetString("UI_SaveImageStatandOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tìm.
        /// </summary>
        public static string UI_Search {
            get {
                return ResourceManager.GetString("UI_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string UI_Shift {
            get {
                return ResourceManager.GetString("UI_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ca.
        /// </summary>
        public static string UI_ShiftDate {
            get {
                return ResourceManager.GetString("UI_ShiftDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm.
        /// </summary>
        public static string UI_Station {
            get {
                return ResourceManager.GetString("UI_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng.
        /// </summary>
        public static string UI_Stop {
            get {
                return ResourceManager.GetString("UI_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _u.
        /// </summary>
        public static string UI_StopShortKey {
            get {
                return ResourceManager.GetString("UI_StopShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string UI_Time {
            get {
                return ResourceManager.GetString("UI_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin phương tiện.
        /// </summary>
        public static string UI_VehicleInfor {
            get {
                return ResourceManager.GetString("UI_VehicleInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình xe làn vào.
        /// </summary>
        public static string UI_VehicleInImage {
            get {
                return ResourceManager.GetString("UI_VehicleInImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Nhập thông tin xe chuẩn.
        /// </summary>
        public static string UI_VehicleInputInfor {
            get {
                return ResourceManager.GetString("UI_VehicleInputInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhậ_p thông tin xe chuẩn.
        /// </summary>
        public static string UI_VehicleInputOutfor {
            get {
                return ResourceManager.GetString("UI_VehicleInputOutfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình xe làn ra.
        /// </summary>
        public static string UI_VehicleOutImage {
            get {
                return ResourceManager.GetString("UI_VehicleOutImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string UI_VehicleType {
            get {
                return ResourceManager.GetString("UI_VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xem chi tiết.
        /// </summary>
        public static string UI_ViewDetail {
            get {
                return ResourceManager.GetString("UI_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe cấm.
        /// </summary>
        public static string Vehicleban {
            get {
                return ResourceManager.GetString("Vehicleban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải trọng.
        /// </summary>
        public static string VehicleLoad {
            get {
                return ResourceManager.GetString("VehicleLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe thường.
        /// </summary>
        public static string VehicleNormal {
            get {
                return ResourceManager.GetString("VehicleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string VehicleNumber {
            get {
                return ResourceManager.GetString("VehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe ưu tiên.
        /// </summary>
        public static string Vehiclepriority {
            get {
                return ResourceManager.GetString("Vehiclepriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phương tiện.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Thống kê lộ trình.
        /// </summary>
        public static string ViewDetail_Title {
            get {
                return ResourceManager.GetString("ViewDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn đầy đủ ngày giờ bắt đầu thống kê !.
        /// </summary>
        public static string WaringHaveNotDataDateFrom {
            get {
                return ResourceManager.GetString("WaringHaveNotDataDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn đầy đủ ngày giờ kết thúc thống kê !.
        /// </summary>
        public static string WaringHaveNotDataDateTo {
            get {
                return ResourceManager.GetString("WaringHaveNotDataDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để xem chi tiết !.
        /// </summary>
        public static string WaringNotDataToShowDetail {
            get {
                return ResourceManager.GetString("WaringNotDataToShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xem chi tiết được vì chưa thống kê !.
        /// </summary>
        public static string WaringNotShowDetail {
            get {
                return ResourceManager.GetString("WaringNotShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn mẩu tin để xem chi tiết !.
        /// </summary>
        public static string WaringPleaseChoseRecordToShowDetail {
            get {
                return ResourceManager.GetString("WaringPleaseChoseRecordToShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu cho thống kê này.Bạn không thể xuất file báo cáo !.
        /// </summary>
        public static string WariningNotDataToExportReport {
            get {
                return ResourceManager.GetString("WariningNotDataToExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xuất file báo cáo vì chưa thống kê !.
        /// </summary>
        public static string WariningNotSearchToExportReport {
            get {
                return ResourceManager.GetString("WariningNotSearchToExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không in được báo cáo vì chưa thống kê !.
        /// </summary>
        public static string WariningNotSearchToPrintReport {
            get {
                return ResourceManager.GetString("WariningNotSearchToPrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày thống kê !.
        /// </summary>
        public static string WarningChooseDate {
            get {
                return ResourceManager.GetString("WarningChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày và đến ngày thống kê phải lớn hơn hoặc bằng 01/01/1900 !.
        /// </summary>
        public static string WarningDateLessThanMinDate {
            get {
                return ResourceManager.GetString("WarningDateLessThanMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu cho thống kê này.Bạn không thể xem báo cáo !.
        /// </summary>
        public static string WarningNotDataShowReport {
            get {
                return ResourceManager.GetString("WarningNotDataShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xe này không có hình xe qua làn. Không thể thực hiện lưu hình chuẩn !.
        /// </summary>
        public static string WarningNotImageRecogToSave {
            get {
                return ResourceManager.GetString("WarningNotImageRecogToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai thẻ.
        /// </summary>
        public static string WrongCard {
            get {
                return ResourceManager.GetString("WrongCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai giá.
        /// </summary>
        public static string WrongPrice {
            get {
                return ResourceManager.GetString("WrongPrice", resourceCulture);
            }
        }
    }
}
