//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa kết nối.
        /// </summary>
        public static string ConfirmDeleteConnection_Caption {
            get {
                return ResourceManager.GetString("ConfirmDeleteConnection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa kêt nối này không?\n\nLưu ý:\nTrường hợp kết nối này đã được sử dụng rồi thì chức này này chỉ xóa tạm chứ không xóa khỏi hệ thống.\nNgược lại nếu chưa được sử dụng thì nó sẽ được xóa khỏi hệ thống !.
        /// </summary>
        public static string ConfirmDeleteConnection_Message {
            get {
                return ResourceManager.GetString("ConfirmDeleteConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa lỗi.
        /// </summary>
        public static string ConfirmDeleteError_Caption {
            get {
                return ResourceManager.GetString("ConfirmDeleteError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa lỗi này không?\n\nLưu ý:\nTrường hợp lỗi này đã được sử dụng rồi thì chức này này chỉ xóa tạm chứ không xóa khỏi hệ thống.\nNgược lại nếu chưa được sử dụng thì nó sẽ được xóa khỏi hệ thống !.
        /// </summary>
        public static string ConfirmDeleteError_Message {
            get {
                return ResourceManager.GetString("ConfirmDeleteError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa định mức.
        /// </summary>
        public static string ConfirmDeleteNorm_Caption {
            get {
                return ResourceManager.GetString("ConfirmDeleteNorm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa định mức này không?\n\nLưu ý:\nTrường hợp định mức này đã được sử dụng rồi thì chức này này chỉ xóa tạm chứ không xóa khỏi hệ thống.\nNgược lại nếu chưa được sử dụng thì nó sẽ được xóa khỏi hệ thống !.
        /// </summary>
        public static string ConfirmDeleteNorm_Message {
            get {
                return ResourceManager.GetString("ConfirmDeleteNorm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ DANH MỤC QUY ĐỊNH KẾT NỐI.
        /// </summary>
        public static string ConnectionCaption {
            get {
                return ResourceManager.GetString("ConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kết nối này đã tồn tại trong CSDL, vui lòng nhập lại mã khác !.
        /// </summary>
        public static string ConnectionIsExist {
            get {
                return ResourceManager.GetString("ConnectionIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kết nối không được để trống !.
        /// </summary>
        public static string ConnectionValidator_ConnectionCode {
            get {
                return ResourceManager.GetString("ConnectionValidator_ConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kết nối không được để trống !.
        /// </summary>
        public static string ConnectionValidator_ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionValidator_ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối CSDL !.
        /// </summary>
        public static string Disconnect_Caption {
            get {
                return ResourceManager.GetString("Disconnect_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không kết nối được với CSDL. \nVui lòng coi lại kết nối hoặc cấu hình lại thông tin !.
        /// </summary>
        public static string Disconnect_Message {
            get {
                return ResourceManager.GetString("Disconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ DANH MỤC LỖI.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã lỗi này đã tồn tại trong CSDL, vui lòng nhập lại mã khác !.
        /// </summary>
        public static string ErrorCodeIsExist {
            get {
                return ResourceManager.GetString("ErrorCodeIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã lỗi không được để trống !.
        /// </summary>
        public static string ErrorValidator_ErrorCode {
            get {
                return ResourceManager.GetString("ErrorValidator_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên lỗi không được để trống !.
        /// </summary>
        public static string ErrorValidator_ErrorName {
            get {
                return ResourceManager.GetString("ErrorValidator_ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl +N : Tạo kết nối mới .
        /// </summary>
        public static string LS_Connection_AddNew {
            get {
                return ResourceManager.GetString("LS_Connection_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + W : Đóng cửa sổ.
        /// </summary>
        public static string LS_Connection_Close {
            get {
                return ResourceManager.GetString("LS_Connection_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mã kết nối.
        /// </summary>
        public static string LS_Connection_ConnectionCode {
            get {
                return ResourceManager.GetString("LS_Connection_ConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string LS_Connection_IsUsed {
            get {
                return ResourceManager.GetString("LS_Connection_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tên kết nối.
        /// </summary>
        public static string LS_Connection_Name {
            get {
                return ResourceManager.GetString("LS_Connection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ghi chú.
        /// </summary>
        public static string LS_Connection_Note {
            get {
                return ResourceManager.GetString("LS_Connection_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + S : Lưu kết nối.
        /// </summary>
        public static string LS_Connection_Save {
            get {
                return ResourceManager.GetString("LS_Connection_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string LS_Connection_Time {
            get {
                return ResourceManager.GetString("LS_Connection_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lần.
        /// </summary>
        public static string LS_Connection_Times {
            get {
                return ResourceManager.GetString("LS_Connection_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục qui định kết nối.
        /// </summary>
        public static string LS_Connection_Title {
            get {
                return ResourceManager.GetString("LS_Connection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + N : Tạo lỗi mới.
        /// </summary>
        public static string LS_Error_AddNew {
            get {
                return ResourceManager.GetString("LS_Error_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + W : Đóng cửa sổ.
        /// </summary>
        public static string LS_Error_Close {
            get {
                return ResourceManager.GetString("LS_Error_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mã lỗi.
        /// </summary>
        public static string LS_Error_ErrorCode {
            get {
                return ResourceManager.GetString("LS_Error_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string LS_Error_IsUsed {
            get {
                return ResourceManager.GetString("LS_Error_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Điểm lỗi.
        /// </summary>
        public static string LS_Error_Mark {
            get {
                return ResourceManager.GetString("LS_Error_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tên lỗi.
        /// </summary>
        public static string LS_Error_Name {
            get {
                return ResourceManager.GetString("LS_Error_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ghi chú.
        /// </summary>
        public static string LS_Error_Note {
            get {
                return ResourceManager.GetString("LS_Error_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + S : Lưu lỗi.
        /// </summary>
        public static string LS_Error_Save {
            get {
                return ResourceManager.GetString("LS_Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục định nghĩa lỗi.
        /// </summary>
        public static string LS_Error_Title {
            get {
                return ResourceManager.GetString("LS_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + N : Tạo định mức mới.
        /// </summary>
        public static string LS_Norm_AddNew {
            get {
                return ResourceManager.GetString("LS_Norm_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + W : Đóng cửa sổ.
        /// </summary>
        public static string LS_Norm_Close {
            get {
                return ResourceManager.GetString("LS_Norm_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string LS_Norm_IsUsed {
            get {
                return ResourceManager.GetString("LS_Norm_IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string LS_Norm_MaxNorm {
            get {
                return ResourceManager.GetString("LS_Norm_MaxNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string LS_Norm_MinNorm {
            get {
                return ResourceManager.GetString("LS_Norm_MinNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tên định mức.
        /// </summary>
        public static string LS_Norm_Name {
            get {
                return ResourceManager.GetString("LS_Norm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mã định mức.
        /// </summary>
        public static string LS_Norm_NormCode {
            get {
                return ResourceManager.GetString("LS_Norm_NormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ghi chú.
        /// </summary>
        public static string LS_Norm_Note {
            get {
                return ResourceManager.GetString("LS_Norm_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Loại sản phẩm.
        /// </summary>
        public static string LS_Norm_ProductType_Name {
            get {
                return ResourceManager.GetString("LS_Norm_ProductType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + S : Lưu định mức.
        /// </summary>
        public static string LS_Norm_Save {
            get {
                return ResourceManager.GetString("LS_Norm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục định mức hàng hóa.
        /// </summary>
        public static string LS_Norm_Title {
            get {
                return ResourceManager.GetString("LS_Norm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị định mức.
        /// </summary>
        public static string LS_Norm_ValueNorm {
            get {
                return ResourceManager.GetString("LS_Norm_ValueNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ DANH MỤC ĐỊNH MỨC HÀNG HÓA.
        /// </summary>
        public static string NormCaption {
            get {
                return ResourceManager.GetString("NormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định mức này đã tồn tại trong CSDL, vui lòng nhập lại mã khác !.
        /// </summary>
        public static string NormCodeIsExist {
            get {
                return ResourceManager.GetString("NormCodeIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định mức không được để trống !.
        /// </summary>
        public static string NormValidator_NormCode {
            get {
                return ResourceManager.GetString("NormValidator_NormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên định mức không được để trống !.
        /// </summary>
        public static string NormValidator_NormName {
            get {
                return ResourceManager.GetString("NormValidator_NormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string NotConfig_Caption {
            get {
                return ResourceManager.GetString("NotConfig_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa cấu hình thông tin truy cập vào cơ sở dữ liệu hoặc thông tin cấu hình bị lỗi.\nVui lòng liên hệ với nhân viên quản trị để cấu hình thông tin !.
        /// </summary>
        public static string NotConfig_Message {
            get {
                return ResourceManager.GetString("NotConfig_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string SaveConfigSuccessful_Caption {
            get {
                return ResourceManager.GetString("SaveConfigSuccessful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thông tin cấu hình CSDL thành công.\nVui lòng khởi động lại chương trình để cấu hình mới có hiệu lực.\nBạn có muốn khởi động lại chương không?.
        /// </summary>
        public static string SaveConfigSuccessful_Message {
            get {
                return ResourceManager.GetString("SaveConfigSuccessful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu qui định kết nối không thành công !.
        /// </summary>
        public static string SaveConnectionUnSuccessful {
            get {
                return ResourceManager.GetString("SaveConnectionUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu định nghĩa lỗi không thành công  !.
        /// </summary>
        public static string SaveErrorUnSuccessful {
            get {
                return ResourceManager.GetString("SaveErrorUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu định mức hàng hóa không thành công !.
        /// </summary>
        public static string SaveNormUnSuccessful {
            get {
                return ResourceManager.GetString("SaveNormUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công !.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu có lỗi !.
        /// </summary>
        public static string SaveUnSuccessful {
            get {
                return ResourceManager.GetString("SaveUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động chuyển kết nối.
        /// </summary>
        public static string SYS_Config_AutoTransfer_Caption {
            get {
                return ResourceManager.GetString("SYS_Config_AutoTransfer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động chuyển sang server dự phòng khi server có vấn đề..
        /// </summary>
        public static string SYS_Config_AutoTransfer_Checkbox {
            get {
                return ResourceManager.GetString("SYS_Config_AutoTransfer_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên _cơ sở dữ liệu.
        /// </summary>
        public static string SYS_Config_Database_FirstDatabase {
            get {
                return ResourceManager.GetString("SYS_Config_Database_FirstDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật _khẩu.
        /// </summary>
        public static string SYS_Config_Database_FirstPassword {
            get {
                return ResourceManager.GetString("SYS_Config_Database_FirstPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên _server chính.
        /// </summary>
        public static string SYS_Config_Database_FirstServer {
            get {
                return ResourceManager.GetString("SYS_Config_Database_FirstServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên _người dùng.
        /// </summary>
        public static string SYS_Config_Database_FirstUsername {
            get {
                return ResourceManager.GetString("SYS_Config_Database_FirstUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cơ _sở dữ liệu.
        /// </summary>
        public static string SYS_Config_Database_SecondDatabase {
            get {
                return ResourceManager.GetString("SYS_Config_Database_SecondDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật k_hẩu.
        /// </summary>
        public static string SYS_Config_Database_SecondPassword {
            get {
                return ResourceManager.GetString("SYS_Config_Database_SecondPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên s_erver dự phòng.
        /// </summary>
        public static string SYS_Config_Database_SecondServer {
            get {
                return ResourceManager.GetString("SYS_Config_Database_SecondServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên n_gười dùng.
        /// </summary>
        public static string SYS_Config_Database_SecondUsername {
            get {
                return ResourceManager.GetString("SYS_Config_Database_SecondUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server chính.
        /// </summary>
        public static string SYS_Config_FirstServer_Caption {
            get {
                return ResourceManager.GetString("SYS_Config_FirstServer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình đường dẫn lưu hình.
        /// </summary>
        public static string SYS_Config_Folder_Caption {
            get {
                return ResourceManager.GetString("SYS_Config_Folder_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình màu.
        /// </summary>
        public static string SYS_Config_Folder_ColorImage {
            get {
                return ResourceManager.GetString("SYS_Config_Folder_ColorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình nhận dạng.
        /// </summary>
        public static string SYS_Config_Folder_RecogImage {
            get {
                return ResourceManager.GetString("SYS_Config_Folder_RecogImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chuẩn.
        /// </summary>
        public static string SYS_Config_Folder_StandardImage {
            get {
                return ResourceManager.GetString("SYS_Config_Folder_StandardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình màn hình giám sát cho trạm.
        /// </summary>
        public static string SYS_Config_Monitor_Caption {
            get {
                return ResourceManager.GetString("SYS_Config_Monitor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm quản lý.
        /// </summary>
        public static string SYS_Config_Monitor_Station {
            get {
                return ResourceManager.GetString("SYS_Config_Monitor_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân hệ cài đặt tại trung tâm.
        /// </summary>
        public static string SYS_Config_Monitor_StationMode {
            get {
                return ResourceManager.GetString("SYS_Config_Monitor_StationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác định nơi mà phân hệ được cài đặt.
        /// </summary>
        public static string SYS_Config_Monitor_StationMode_Caption {
            get {
                return ResourceManager.GetString("SYS_Config_Monitor_StationMode_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server dự phòng.
        /// </summary>
        public static string SYS_Config_SecondServer_Caption {
            get {
                return ResourceManager.GetString("SYS_Config_SecondServer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string UI_Notice {
            get {
                return ResourceManager.GetString("UI_Notice", resourceCulture);
            }
        }
    }
}
