//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupervisionTrafficReportViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupervisionTrafficReportViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.SupervisionTrafficReportViewResource", typeof(SupervisionTrafficReportViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ nhật.
        /// </summary>
        public static string Chart_Sunday {
            get {
                return ResourceManager.GetString("Chart_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin màn hình đã được  lưu thành công. Bạn có muốn xem tập tin đã xuất ?.
        /// </summary>
        public static string Export_Complete {
            get {
                return ResourceManager.GetString("Export_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Document(.pdf)|*.pdf.
        /// </summary>
        public static string Export_PDF_Filter {
            get {
                return ResourceManager.GetString("Export_PDF_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Export_PDF_Title {
            get {
                return ResourceManager.GetString("Export_PDF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file thất bại !.
        /// </summary>
        public static string Export_UnSuccessful {
            get {
                return ResourceManager.GetString("Export_UnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin excel đã được xuất thành công. Bạn có muốn xem tập tin đã xuất ?.
        /// </summary>
        public static string ExportExcel_Successful {
            get {
                return ResourceManager.GetString("ExportExcel_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Report Fail.
        /// </summary>
        public static string Log_Report_Export_Fail {
            get {
                return ResourceManager.GetString("Log_Report_Export_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF Fail.
        /// </summary>
        public static string Log_Report_ExportPDF_Fail {
            get {
                return ResourceManager.GetString("Log_Report_ExportPDF_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải nhỏ hơn ngày kết thúc !.
        /// </summary>
        public static string Message_Error_FromDate_MustBeLessThan_ToDate {
            get {
                return ResourceManager.GetString("Message_Error_FromDate_MustBeLessThan_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu phải nhỏ hơn giờ kết thúc !.
        /// </summary>
        public static string Message_Error_FromTime_MustBeLessThan_ToTime {
            get {
                return ResourceManager.GetString("Message_Error_FromTime_MustBeLessThan_ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm thống kê phải trước giờ hiện tại !.
        /// </summary>
        public static string Message_Error_Time {
            get {
                return ResourceManager.GetString("Message_Error_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm thống kê phải trước ngày hiện tại .
        /// </summary>
        public static string Message_Error_Time_MustBeLessThan_Now {
            get {
                return ResourceManager.GetString("Message_Error_Time_MustBeLessThan_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bắt đâu phải nhỏ hơn ngày kết thúc !.
        /// </summary>
        public static string Message_Error_Time_MustBeLessThan_Now_Time {
            get {
                return ResourceManager.GetString("Message_Error_Time_MustBeLessThan_Now_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm thống kê quá nhỏ so với thực tế !.
        /// </summary>
        public static string Message_Error_Time_TooSmall {
            get {
                return ResourceManager.GetString("Message_Error_Time_TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tuần không hợp lệ !.
        /// </summary>
        public static string Message_Error_Week_Invalid {
            get {
                return ResourceManager.GetString("Message_Error_Week_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu cho thống kê này !.
        /// </summary>
        public static string Message_NotData {
            get {
                return ResourceManager.GetString("Message_NotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu cho thống kê này. Bạn không thể in được !.
        /// </summary>
        public static string Message_NotData_4Printing {
            get {
                return ResourceManager.GetString("Message_NotData_4Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu không thành công.
        /// </summary>
        public static string Message_Save_NotSuccess {
            get {
                return ResourceManager.GetString("Message_Save_NotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công.
        /// </summary>
        public static string Message_Save_Success {
            get {
                return ResourceManager.GetString("Message_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thống kê trước khi xem in báo cáo !.
        /// </summary>
        public static string Message_warning_print_report {
            get {
                return ResourceManager.GetString("Message_warning_print_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: {0}.
        /// </summary>
        public static string Report_Address_P {
            get {
                return ResourceManager.GetString("Report_Address_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty: {0}.
        /// </summary>
        public static string Report_CompanyName_P {
            get {
                return ResourceManager.GetString("Report_CompanyName_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ngày).
        /// </summary>
        public static string Report_Date {
            get {
                return ResourceManager.GetString("Report_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày {0} - Ca {1}.
        /// </summary>
        public static string Report_DateAndShift_P {
            get {
                return ResourceManager.GetString("Report_DateAndShift_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu ngày tháng sai.\n Xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string Report_DateThanOrEqual4 {
            get {
                return ResourceManager.GetString("Report_DateThanOrEqual4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Làn).
        /// </summary>
        public static string Report_Day {
            get {
                return ResourceManager.GetString("Report_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ DOANH THU\n{0}.
        /// </summary>
        public static string Report_DoanhThu_Title_P {
            get {
                return ResourceManager.GetString("Report_DoanhThu_Title_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: {0}.
        /// </summary>
        public static string Report_Email_P {
            get {
                return ResourceManager.GetString("Report_Email_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax: {0}.
        /// </summary>
        public static string Report_Fax_P {
            get {
                return ResourceManager.GetString("Report_Fax_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng ngày tháng bắt đầu sai !.
        /// </summary>
        public static string Report_FormatFromDateWrong {
            get {
                return ResourceManager.GetString("Report_FormatFromDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng ngày tháng kết thúc thống kê sai !.
        /// </summary>
        public static string Report_FormatToDateWrong {
            get {
                return ResourceManager.GetString("Report_FormatToDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ {0} đến nay.
        /// </summary>
        public static string Report_FromTimeToNow_P {
            get {
                return ResourceManager.GetString("Report_FromTimeToNow_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ  {0} đến {1}.
        /// </summary>
        public static string Report_FromTimeToTime_P {
            get {
                return ResourceManager.GetString("Report_FromTimeToTime_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ SỐ LƯỢNG HÀNG HÓA\n{0}.
        /// </summary>
        public static string Report_goods {
            get {
                return ResourceManager.GetString("Report_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Lượt xe).
        /// </summary>
        public static string Report_LuotXe {
            get {
                return ResourceManager.GetString("Report_LuotXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Tháng).
        /// </summary>
        public static string Report_Month {
            get {
                return ResourceManager.GetString("Report_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày bắt đầu thống kê !.
        /// </summary>
        public static string Report_NotDataFromDate {
            get {
                return ResourceManager.GetString("Report_NotDataFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày kết thúc thống kê !.
        /// </summary>
        public static string Report_NotDataToDate {
            get {
                return ResourceManager.GetString("Report_NotDataToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày thống kê theo ca !.
        /// </summary>
        public static string Report_NotDataToDayShift {
            get {
                return ResourceManager.GetString("Report_NotDataToDayShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string Report_PrintTime_Format {
            get {
                return ResourceManager.GetString("Report_PrintTime_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê lúc {0}.
        /// </summary>
        public static string Report_SummaryAt {
            get {
                return ResourceManager.GetString("Report_SummaryAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxCode: {0}.
        /// </summary>
        public static string Report_TaxCode_P {
            get {
                return ResourceManager.GetString("Report_TaxCode_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại: {0}.
        /// </summary>
        public static string Report_Telephone_P {
            get {
                return ResourceManager.GetString("Report_Telephone_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng {0} năm {1}.
        /// </summary>
        public static string Report_Title_Time_DayMonth_P {
            get {
                return ResourceManager.GetString("Report_Title_Time_DayMonth_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày {0} tháng {1} năm {2}.
        /// </summary>
        public static string Report_Title_Time_DayWeek_P {
            get {
                return ResourceManager.GetString("Report_Title_Time_DayWeek_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm {0}.
        /// </summary>
        public static string Report_Title_Time_MonthYear_P {
            get {
                return ResourceManager.GetString("Report_Title_Time_MonthYear_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quí {0} năm {1}.
        /// </summary>
        public static string Report_Title_Time_QuaterYear_P {
            get {
                return ResourceManager.GetString("Report_Title_Time_QuaterYear_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng lượng hàng hóa.
        /// </summary>
        public static string Report_TotalGoods {
            get {
                return ResourceManager.GetString("Report_TotalGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        public static string Report_TotalMoney {
            get {
                return ResourceManager.GetString("Report_TotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (đồng).
        /// </summary>
        public static string Report_TrieuDong {
            get {
                return ResourceManager.GetString("Report_TrieuDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem báo cáo không thành công !.
        /// </summary>
        public static string Report_UnSuccessful {
            get {
                return ResourceManager.GetString("Report_UnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website: {0}.
        /// </summary>
        public static string Report_Website_P {
            get {
                return ResourceManager.GetString("Report_Website_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỐNG KÊ LƯU LƯỢNG XE QUA LÀN \n{0}.
        /// </summary>
        public static string Report_XeQuaLan_Title_P {
            get {
                return ResourceManager.GetString("Report_XeQuaLan_Title_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19000101.
        /// </summary>
        public static string SQL_MINDATE {
            get {
                return ResourceManager.GetString("SQL_MINDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng xe qua làn.
        /// </summary>
        public static string TrafficVehicleLane {
            get {
                return ResourceManager.GetString("TrafficVehicleLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th_oát.
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _o.
        /// </summary>
        public static string UI_Close_ShortKey {
            get {
                return ResourceManager.GetString("UI_Close_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string UI_Date {
            get {
                return ResourceManager.GetString("UI_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ca.
        /// </summary>
        public static string UI_DateAndShift {
            get {
                return ResourceManager.GetString("UI_DateAndShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string UI_FromDate {
            get {
                return ResourceManager.GetString("UI_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string UI_Month {
            get {
                return ResourceManager.GetString("UI_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cấu hình trạm trước khi chọn thống kê !.
        /// </summary>
        public static string UI_NotConfigurationStationID {
            get {
                return ResourceManager.GetString("UI_NotConfigurationStationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trực tuyến.
        /// </summary>
        public static string UI_Online {
            get {
                return ResourceManager.GetString("UI_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _In báo cáo.
        /// </summary>
        public static string UI_PrintReport {
            get {
                return ResourceManager.GetString("UI_PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quí.
        /// </summary>
        public static string UI_QuarterYear {
            get {
                return ResourceManager.GetString("UI_QuarterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string UI_Shift {
            get {
                return ResourceManager.GetString("UI_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xem báo cáo.
        /// </summary>
        public static string UI_ShowReport {
            get {
                return ResourceManager.GetString("UI_ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm.
        /// </summary>
        public static string UI_Station {
            get {
                return ResourceManager.GetString("UI_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Thống kê.
        /// </summary>
        public static string UI_Summary {
            get {
                return ResourceManager.GetString("UI_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string UI_Time {
            get {
                return ResourceManager.GetString("UI_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cập nhật.
        /// </summary>
        public static string UI_Time4Update {
            get {
                return ResourceManager.GetString("UI_Time4Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string UI_ToDate {
            get {
                return ResourceManager.GetString("UI_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần.
        /// </summary>
        public static string UI_Week {
            get {
                return ResourceManager.GetString("UI_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string UI_Year {
            get {
                return ResourceManager.GetString("UI_Year", resourceCulture);
            }
        }
    }
}
