//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupervisionString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupervisionString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.SupervisionString", typeof(SupervisionString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  begin Connect to webservice.........
        /// </summary>
        public static string BeginConnectService {
            get {
                return ResourceManager.GetString("BeginConnectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Connect to Webservice Fail.
        /// </summary>
        public static string ConnectServiceFail {
            get {
                return ResourceManager.GetString("ConnectServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Connect to Webservice successfull..
        /// </summary>
        public static string ConnectServiceSuccesss {
            get {
                return ResourceManager.GetString("ConnectServiceSuccesss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thiết bị tại làn này đã bị vô hiệu lực !.
        /// </summary>
        public static string DeviceIsDisable {
            get {
                return ResourceManager.GetString("DeviceIsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kết nối tới Webservice thất bại !.
        /// </summary>
        public static string MessageConnectServiceFail {
            get {
                return ResourceManager.GetString("MessageConnectServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t Not send ErrorMessage because :.
        /// </summary>
        public static string MessageSendErrorInfor {
            get {
                return ResourceManager.GetString("MessageSendErrorInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chưa cấu hình trạm để theo dõi. Vui lòng cấu hình trước khi chọn chức năng này !.
        /// </summary>
        public static string MonitorNotConfig {
            get {
                return ResourceManager.GetString("MonitorNotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chưa có hình ảnh để chấm lỗi !.
        /// </summary>
        public static string NotImage {
            get {
                return ResourceManager.GetString("NotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền kiểm không hợp lệ..
        /// </summary>
        public static string ResultCheckVehicleFail {
            get {
                return ResourceManager.GetString("ResultCheckVehicleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác định ( không có thông tin trong CSDL phương tiện).
        /// </summary>
        public static string ResultCheckVehicleNoneStatus {
            get {
                return ResourceManager.GetString("ResultCheckVehicleNoneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xem xét.
        /// </summary>
        public static string ResultCheckVehicleReview {
            get {
                return ResourceManager.GetString("ResultCheckVehicleReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tiền kiểm hợp lệ..
        /// </summary>
        public static string ResultCheckVehicleSuccess {
            get {
                return ResourceManager.GetString("ResultCheckVehicleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thông tin lỗi gửi đi đã thất bại !.
        /// </summary>
        public static string SendErrorInfo {
            get {
                return ResourceManager.GetString("SendErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Write ErrorVehichleInfor ToDataBase fail:.
        /// </summary>
        public static string WriteErrorInfoToDatabaseFail {
            get {
                return ResourceManager.GetString("WriteErrorInfoToDatabaseFail", resourceCulture);
            }
        }
    }
}
