//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VehicleTurnViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleTurnViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.VehicleTurnViewResource", typeof(VehicleTurnViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa hậu kiểm.
        /// </summary>
        public static string DanhGia_ChuaHauKiem {
            get {
                return ResourceManager.GetString("DanhGia_ChuaHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hậu kiểm.
        /// </summary>
        public static string DanhGia_DaHauKiem {
            get {
                return ResourceManager.GetString("DanhGia_DaHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xem xét.
        /// </summary>
        public static string DanhGia_DangXemXet {
            get {
                return ResourceManager.GetString("DanhGia_DangXemXet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ.
        /// </summary>
        public static string DanhGia_HopLe {
            get {
                return ResourceManager.GetString("DanhGia_HopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ.
        /// </summary>
        public static string DanhGia_KhongHopLe {
            get {
                return ResourceManager.GetString("DanhGia_KhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ tài chính (BTC).
        /// </summary>
        public static string DoiTuong_BTC {
            get {
                return ResourceManager.GetString("DoiTuong_BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU.
        /// </summary>
        public static string DoiTuong_OBU {
            get {
                return ResourceManager.GetString("DoiTuong_OBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU 2 mãnh.
        /// </summary>
        public static string DoiTuong_OBU2Piece {
            get {
                return ResourceManager.GetString("DoiTuong_OBU2Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBU thời gian.
        /// </summary>
        public static string DoiTuong_OBUThoiGian {
            get {
                return ResourceManager.GetString("DoiTuong_OBUThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Card.
        /// </summary>
        public static string DoiTuong_SmartCard {
            get {
                return ResourceManager.GetString("DoiTuong_SmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string DoiTuong_TatCa {
            get {
                return ResourceManager.GetString("DoiTuong_TatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên 1 Xe.
        /// </summary>
        public static string DoiTuong_UuTien1Xe {
            get {
                return ResourceManager.GetString("DoiTuong_UuTien1Xe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên đoàn xe.
        /// </summary>
        public static string DoiTuong_UuTienDoanXe {
            get {
                return ResourceManager.GetString("DoiTuong_UuTienDoanXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé lượt.
        /// </summary>
        public static string DoiTuong_VeLuot {
            get {
                return ResourceManager.GetString("DoiTuong_VeLuot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé thời gian.
        /// </summary>
        public static string DoiTuong_VeThoiGian {
            get {
                return ResourceManager.GetString("DoiTuong_VeThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load content fail.
        /// </summary>
        public static string Log_LoadTypeOfHauKiem {
            get {
                return ResourceManager.GetString("Log_LoadTypeOfHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phải nhỏ hơn ngày hiện tại !.
        /// </summary>
        public static string Message_Error_Date_MustBeLessThan_ToDate {
            get {
                return ResourceManager.GetString("Message_Error_Date_MustBeLessThan_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải nhỏ hơn ngày kết thúc !.
        /// </summary>
        public static string Message_Error_FromDate_MustBeLessThan_ToDate {
            get {
                return ResourceManager.GetString("Message_Error_FromDate_MustBeLessThan_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải nhỏ hơn ngày hiện tại !.
        /// </summary>
        public static string Message_Error_Time_MustBeLessThan_Now {
            get {
                return ResourceManager.GetString("Message_Error_Time_MustBeLessThan_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm thống kê quá nhỏ so với thực tế !.
        /// </summary>
        public static string Message_Error_Time_TooSmall {
            get {
                return ResourceManager.GetString("Message_Error_Time_TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số mẫu tin không hợp lệ. Xin vui lòng nhập lại !.
        /// </summary>
        public static string Message_IndexRecordNotValid {
            get {
                return ResourceManager.GetString("Message_IndexRecordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn nhập số mẫu tin lớn hơn tổng số mẫu tin. Xin vui lòng nhập lại !.
        /// </summary>
        public static string Message_IndexRecordOverFlow {
            get {
                return ResourceManager.GetString("Message_IndexRecordOverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu cho điều kiện thống kê bạn chọn !.
        /// </summary>
        public static string Message_NoData {
            get {
                return ResourceManager.GetString("Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19000101.
        /// </summary>
        public static string SQL_MINDATE {
            get {
                return ResourceManager.GetString("SQL_MINDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckBtc.
        /// </summary>
        public static string Table_IN_CheckBtc {
            get {
                return ResourceManager.GetString("Table_IN_CheckBtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckForceOpen.
        /// </summary>
        public static string Table_IN_CheckForceOpen {
            get {
                return ResourceManager.GetString("Table_IN_CheckForceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckForceOpenGroup.
        /// </summary>
        public static string Table_IN_CheckForceOpenGroup {
            get {
                return ResourceManager.GetString("Table_IN_CheckForceOpenGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckForceOpenGroupDetail.
        /// </summary>
        public static string Table_IN_CheckForceOpenGroupDetail {
            get {
                return ResourceManager.GetString("Table_IN_CheckForceOpenGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckObu.
        /// </summary>
        public static string Table_IN_CheckObu {
            get {
                return ResourceManager.GetString("Table_IN_CheckObu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckObuSmartCard.
        /// </summary>
        public static string Table_IN_CheckObuSmartCard {
            get {
                return ResourceManager.GetString("Table_IN_CheckObuSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckPeriodObu.
        /// </summary>
        public static string Table_IN_CheckPeriodObu {
            get {
                return ResourceManager.GetString("Table_IN_CheckPeriodObu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckPeriodTicket.
        /// </summary>
        public static string Table_IN_CheckPeriodTicket {
            get {
                return ResourceManager.GetString("Table_IN_CheckPeriodTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckSmartCard.
        /// </summary>
        public static string Table_IN_CheckSmartCard {
            get {
                return ResourceManager.GetString("Table_IN_CheckSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN_CheckTicket.
        /// </summary>
        public static string Table_IN_CheckTicket {
            get {
                return ResourceManager.GetString("Table_IN_CheckTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckBtc.
        /// </summary>
        public static string Table_OUT_CheckBtc {
            get {
                return ResourceManager.GetString("Table_OUT_CheckBtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckForceOpen.
        /// </summary>
        public static string Table_OUT_CheckForceOpen {
            get {
                return ResourceManager.GetString("Table_OUT_CheckForceOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckForceOpenGroup.
        /// </summary>
        public static string Table_OUT_CheckForceOpenGroup {
            get {
                return ResourceManager.GetString("Table_OUT_CheckForceOpenGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckForceOpenGroupDetail.
        /// </summary>
        public static string Table_OUT_CheckForceOpenGroupDetail {
            get {
                return ResourceManager.GetString("Table_OUT_CheckForceOpenGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckObu.
        /// </summary>
        public static string Table_OUT_CheckObu {
            get {
                return ResourceManager.GetString("Table_OUT_CheckObu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckObuSmartCard.
        /// </summary>
        public static string Table_OUT_CheckObuSmartCard {
            get {
                return ResourceManager.GetString("Table_OUT_CheckObuSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckPeriodObu.
        /// </summary>
        public static string Table_OUT_CheckPeriodObu {
            get {
                return ResourceManager.GetString("Table_OUT_CheckPeriodObu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckPeriodTicket.
        /// </summary>
        public static string Table_OUT_CheckPeriodTicket {
            get {
                return ResourceManager.GetString("Table_OUT_CheckPeriodTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckSmartCard.
        /// </summary>
        public static string Table_OUT_CheckSmartCard {
            get {
                return ResourceManager.GetString("Table_OUT_CheckSmartCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT_CheckTicket.
        /// </summary>
        public static string Table_OUT_CheckTicket {
            get {
                return ResourceManager.GetString("Table_OUT_CheckTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string TitleMessageBox {
            get {
                return ResourceManager.GetString("TitleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string UI_2Cham {
            get {
                return ResourceManager.GetString("UI_2Cham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string UI_ALL {
            get {
                return ResourceManager.GetString("UI_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các lượt hậu kiểm.
        /// </summary>
        public static string UI_CacLuotHauKiem {
            get {
                return ResourceManager.GetString("UI_CacLuotHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm lỗi.
        /// </summary>
        public static string UI_ChamLoi {
            get {
                return ResourceManager.GetString("UI_ChamLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa hậu kiểm.
        /// </summary>
        public static string UI_ChuaHauKiem {
            get {
                return ResourceManager.GetString("UI_ChuaHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ phương tiện.
        /// </summary>
        public static string UI_ChuPhuongTien {
            get {
                return ResourceManager.GetString("UI_ChuPhuongTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Đóng.
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm soát.
        /// </summary>
        public static string UI_Control {
            get {
                return ResourceManager.GetString("UI_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hậu kiểm.
        /// </summary>
        public static string UI_DaHauKiem {
            get {
                return ResourceManager.GetString("UI_DaHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xem xét.
        /// </summary>
        public static string UI_DangXemXet {
            get {
                return ResourceManager.GetString("UI_DangXemXet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        public static string UI_DanhGia {
            get {
                return ResourceManager.GetString("UI_DanhGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string UI_Date {
            get {
                return ResourceManager.GetString("UI_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ca.
        /// </summary>
        public static string UI_DateShift {
            get {
                return ResourceManager.GetString("UI_DateShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string UI_DiaChi {
            get {
                return ResourceManager.GetString("UI_DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        public static string UI_DoiTuong {
            get {
                return ResourceManager.GetString("UI_DoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dừng.
        /// </summary>
        public static string UI_Dung {
            get {
                return ResourceManager.GetString("UI_Dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string UI_Employee {
            get {
                return ResourceManager.GetString("UI_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất _Excel .
        /// </summary>
        public static string UI_ExportExcel {
            get {
                return ResourceManager.GetString("UI_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện thống kê.
        /// </summary>
        public static string UI_FilterParamater {
            get {
                return ResourceManager.GetString("UI_FilterParamater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string UI_FromDate {
            get {
                return ResourceManager.GetString("UI_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string UI_GhiChu {
            get {
                return ResourceManager.GetString("UI_GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} giây chuyển lượt.
        /// </summary>
        public static string UI_GiayChuyenLuot {
            get {
                return ResourceManager.GetString("UI_GiayChuyenLuot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ.
        /// </summary>
        public static string UI_Grid_DateTime {
            get {
                return ResourceManager.GetString("UI_Grid_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string UI_Grid_GhiChu {
            get {
                return ResourceManager.GetString("UI_Grid_GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả hậu kiểm.
        /// </summary>
        public static string UI_Grid_KetQuaHauKiem {
            get {
                return ResourceManager.GetString("UI_Grid_KetQuaHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string UI_Grid_KhachHang {
            get {
                return ResourceManager.GetString("UI_Grid_KhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn.
        /// </summary>
        public static string UI_Grid_Lane {
            get {
                return ResourceManager.GetString("UI_Grid_Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đối tượng.
        /// </summary>
        public static string UI_Grid_LoaiDoiTuong {
            get {
                return ResourceManager.GetString("UI_Grid_LoaiDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thiết bị.
        /// </summary>
        public static string UI_Grid_LoaiThietBi {
            get {
                return ResourceManager.GetString("UI_Grid_LoaiThietBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thẻ ưu tiên.
        /// </summary>
        public static string UI_Grid_LoaiUuTien {
            get {
                return ResourceManager.GetString("UI_Grid_LoaiUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại vé.
        /// </summary>
        public static string UI_Grid_LoaiVe {
            get {
                return ResourceManager.GetString("UI_Grid_LoaiVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt hậu kiểm.
        /// </summary>
        public static string UI_Grid_LuotHauKiem {
            get {
                return ResourceManager.GetString("UI_Grid_LuotHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string UI_Grid_MaDoiTuong {
            get {
                return ResourceManager.GetString("UI_Grid_MaDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ ưu tiên.
        /// </summary>
        public static string UI_Grid_MaTheUuTien {
            get {
                return ResourceManager.GetString("UI_Grid_MaTheUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string UI_Grid_MaThietBi {
            get {
                return ResourceManager.GetString("UI_Grid_MaThietBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vé.
        /// </summary>
        public static string UI_Grid_MaVe {
            get {
                return ResourceManager.GetString("UI_Grid_MaVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        public static string UI_Grid_MenhGia {
            get {
                return ResourceManager.GetString("UI_Grid_MenhGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ hậu kiểm.
        /// </summary>
        public static string UI_Grid_NgayGioHauKiem {
            get {
                return ResourceManager.GetString("UI_Grid_NgayGioHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string UI_Grid_NgayHetHan {
            get {
                return ResourceManager.GetString("UI_Grid_NgayHetHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiệu lực.
        /// </summary>
        public static string UI_Grid_NgayHieuLuc {
            get {
                return ResourceManager.GetString("UI_Grid_NgayHieuLuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên hậu kiểm.
        /// </summary>
        public static string UI_Grid_NhanVienHauKiem {
            get {
                return ResourceManager.GetString("UI_Grid_NhanVienHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên soát.
        /// </summary>
        public static string UI_Grid_NhanVienSoat {
            get {
                return ResourceManager.GetString("UI_Grid_NhanVienSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string UI_Grid_Shift {
            get {
                return ResourceManager.GetString("UI_Grid_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền trừ.
        /// </summary>
        public static string UI_Grid_SoTienTru {
            get {
                return ResourceManager.GetString("UI_Grid_SoTienTru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string UI_Grid_SoXe {
            get {
                return ResourceManager.GetString("UI_Grid_SoXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe đăng ký.
        /// </summary>
        public static string UI_Grid_SoXeDangKy {
            get {
                return ResourceManager.GetString("UI_Grid_SoXeDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string UI_Grid_STT {
            get {
                return ResourceManager.GetString("UI_Grid_STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn vé đến.
        /// </summary>
        public static string UI_Grid_ThoiHanVeDen {
            get {
                return ResourceManager.GetString("UI_Grid_ThoiHanVeDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn vé từ.
        /// </summary>
        public static string UI_Grid_ThoiHanVeTu {
            get {
                return ResourceManager.GetString("UI_Grid_ThoiHanVeTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đánh giá.
        /// </summary>
        public static string UI_HeThongDanhGia {
            get {
                return ResourceManager.GetString("UI_HeThongDanhGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống hậu kiểm.
        /// </summary>
        public static string UI_HeThongHauKiem {
            get {
                return ResourceManager.GetString("UI_HeThongHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình.
        /// </summary>
        public static string UI_Hinh {
            get {
                return ResourceManager.GetString("UI_Hinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình xe chuẩn.
        /// </summary>
        public static string UI_HinhXeChuan {
            get {
                return ResourceManager.GetString("UI_HinhXeChuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình xe qua làn.
        /// </summary>
        public static string UI_HinhXeQuaLan {
            get {
                return ResourceManager.GetString("UI_HinhXeQuaLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ.
        /// </summary>
        public static string UI_HopLe {
            get {
                return ResourceManager.GetString("UI_HopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ.
        /// </summary>
        public static string UI_KhongHopLe {
            get {
                return ResourceManager.GetString("UI_KhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn.
        /// </summary>
        public static string UI_Lane {
            get {
                return ResourceManager.GetString("UI_Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đối tượng.
        /// </summary>
        public static string UI_LoaiDoiTuong {
            get {
                return ResourceManager.GetString("UI_LoaiDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string UI_LoaiPhuongTien {
            get {
                return ResourceManager.GetString("UI_LoaiPhuongTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string UI_Loi {
            get {
                return ResourceManager.GetString("UI_Loi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string UI_MaDoiTuong {
            get {
                return ResourceManager.GetString("UI_MaDoiTuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ ưu tiên.
        /// </summary>
        public static string UI_MaTheUuTien {
            get {
                return ResourceManager.GetString("UI_MaTheUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết bị.
        /// </summary>
        public static string UI_MaThietBi {
            get {
                return ResourceManager.GetString("UI_MaThietBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vé.
        /// </summary>
        public static string UI_MaVe {
            get {
                return ResourceManager.GetString("UI_MaVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        public static string UI_MenhGia {
            get {
                return ResourceManager.GetString("UI_MenhGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng ký.
        /// </summary>
        public static string UI_NgayDangKy {
            get {
                return ResourceManager.GetString("UI_NgayDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đánh giá.
        /// </summary>
        public static string UI_NhanVienDanhGia {
            get {
                return ResourceManager.GetString("UI_NhanVienDanhGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên hậu kiểm.
        /// </summary>
        public static string UI_NhanVienHauKiem {
            get {
                return ResourceManager.GetString("UI_NhanVienHauKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tìm.
        /// </summary>
        public static string UI_Search {
            get {
                return ResourceManager.GetString("UI_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string UI_Shift {
            get {
                return ResourceManager.GetString("UI_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chỗ.
        /// </summary>
        public static string UI_SoCho {
            get {
                return ResourceManager.GetString("UI_SoCho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền trừ.
        /// </summary>
        public static string UI_SoTienTru {
            get {
                return ResourceManager.GetString("UI_SoTienTru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string UI_SoXe {
            get {
                return ResourceManager.GetString("UI_SoXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe nhận dạng.
        /// </summary>
        public static string UI_SoXeNhanDang {
            get {
                return ResourceManager.GetString("UI_SoXeNhanDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm.
        /// </summary>
        public static string UI_Station {
            get {
                return ResourceManager.GetString("UI_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải trọng.
        /// </summary>
        public static string UI_TaiTrong {
            get {
                return ResourceManager.GetString("UI_TaiTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin kiểm soát.
        /// </summary>
        public static string UI_ThongTinKiemSoat {
            get {
                return ResourceManager.GetString("UI_ThongTinKiemSoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin phương tiện.
        /// </summary>
        public static string UI_ThongTinPhuongTien {
            get {
                return ResourceManager.GetString("UI_ThongTinPhuongTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string UI_Time {
            get {
                return ResourceManager.GetString("UI_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string UI_ToDate {
            get {
                return ResourceManager.GetString("UI_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên 1 xe.
        /// </summary>
        public static string UI_UuTien1Xe {
            get {
                return ResourceManager.GetString("UI_UuTien1Xe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên đoàn xe.
        /// </summary>
        public static string UI_UuTienDoanXe {
            get {
                return ResourceManager.GetString("UI_UuTienDoanXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé Quí.
        /// </summary>
        public static string UI_VeQui {
            get {
                return ResourceManager.GetString("UI_VeQui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé Tháng.
        /// </summary>
        public static string UI_VeThang {
            get {
                return ResourceManager.GetString("UI_VeThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xem chi tiết.
        /// </summary>
        public static string UI_ViewDetail {
            get {
                return ResourceManager.GetString("UI_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe ưu tiên.
        /// </summary>
        public static string UI_XeUuTien {
            get {
                return ResourceManager.GetString("UI_XeUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé lượt.
        /// </summary>
        public static string VE_LUOT {
            get {
                return ResourceManager.GetString("VE_LUOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé quí.
        /// </summary>
        public static string VE_QUI {
            get {
                return ResourceManager.GetString("VE_QUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vé tháng.
        /// </summary>
        public static string VE_THANG {
            get {
                return ResourceManager.GetString("VE_THANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string View_Detail {
            get {
                return ResourceManager.GetString("View_Detail", resourceCulture);
            }
        }
    }
}
