//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VehicleInformationAllString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleInformationAllString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanProject.Properties.VehicleInformationAllString", typeof(VehicleInformationAllString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo _mới.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các loại.
        /// </summary>
        public static string AllCheckType {
            get {
                return ResourceManager.GetString("AllCheckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string AllInformation {
            get {
                return ResourceManager.GetString("AllInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đăng kiểm.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đăng kiểm là giá trị dương!.
        /// </summary>
        public static string AmountInteger {
            get {
                return ResourceManager.GetString("AmountInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vùng.
        /// </summary>
        public static string Areacode {
            get {
                return ResourceManager.GetString("Areacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vùng không hợp lệ !.
        /// </summary>
        public static string AreacodeNotValidate {
            get {
                return ResourceManager.GetString("AreacodeNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện tìm kiếm.
        /// </summary>
        public static string ConditionSearch {
            get {
                return ResourceManager.GetString("ConditionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa cơ sở dữ liệu chuẩn.
        /// </summary>
        public static string ConfirmDeleteNorm_Caption {
            get {
                return ResourceManager.GetString("ConfirmDeleteNorm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tháng không được để trống!.
        /// </summary>
        public static string DateTimeNotSpace {
            get {
                return ResourceManager.GetString("DateTimeNotSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên cập nhật.
        /// </summary>
        public static string EmployUpdate {
            get {
                return ResourceManager.GetString("EmployUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe này đã tồn tại trong cơ sở dữ liệu!.
        /// </summary>
        public static string Error_NotEdit {
            get {
                return ResourceManager.GetString("Error_NotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe không hợp lệ!.
        /// </summary>
        public static string Error_Number {
            get {
                return ResourceManager.GetString("Error_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe định dạng sai!.
        /// </summary>
        public static string ErrorRegisplate {
            get {
                return ResourceManager.GetString("ErrorRegisplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Đóng.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervision openfile (*.mdb)|*.mdb.
        /// </summary>
        public static string FileOpenTitle {
            get {
                return ResourceManager.GetString("FileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập cơ sở dữ liệu chuẩn.
        /// </summary>
        public static string InputDatabaseStand {
            get {
                return ResourceManager.GetString("InputDatabaseStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập cơ sở dữ liệu đăng kiểm.
        /// </summary>
        public static string InputDataRegis {
            get {
                return ResourceManager.GetString("InputDataRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe ưu tiên.
        /// </summary>
        public static string Isforce {
            get {
                return ResourceManager.GetString("Isforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe cấm.
        /// </summary>
        public static string IsIllage {
            get {
                return ResourceManager.GetString("IsIllage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe thường.
        /// </summary>
        public static string IsNormal {
            get {
                return ResourceManager.GetString("IsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi load dữ listViewItem ở ListInputDataViewModel.
        /// </summary>
        public static string Log_errorLoadListViewItem_ListInputOutPut {
            get {
                return ResourceManager.GetString("Log_errorLoadListViewItem_ListInputOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi session.
        /// </summary>
        public static string log_errorSession {
            get {
                return ResourceManager.GetString("log_errorSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi unsession..
        /// </summary>
        public static string log_errorUnsession {
            get {
                return ResourceManager.GetString("log_errorUnsession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdb.
        /// </summary>
        public static string mdb {
            get {
                return ResourceManager.GetString("mdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày phải nhỏ hơn đến ngày!.
        /// </summary>
        public static string Message_Error_Time_MustBeLessThan_Now {
            get {
                return ResourceManager.GetString("Message_Error_Time_MustBeLessThan_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời điểm nhập quá nhỏ so với thực tế. Xin vui lòng nhập lại!.
        /// </summary>
        public static string Message_Error_Time_TooSmall {
            get {
                return ResourceManager.GetString("Message_Error_Time_TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn xóa thông tin phương tiện được chọn?.
        /// </summary>
        public static string MessageNotDelete {
            get {
                return ResourceManager.GetString("MessageNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đến phải nhỏ hơn ngày hiện tại!.
        /// </summary>
        public static string MorethanDateTime {
            get {
                return ResourceManager.GetString("MorethanDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chỗ quá lớn !.
        /// </summary>
        public static string MoreThanSeat {
            get {
                return ResourceManager.GetString("MoreThanSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chổ không hợp lệ. Số chổ có giá trị từ 1 đến 100 !.
        /// </summary>
        public static string MorethanSeate {
            get {
                return ResourceManager.GetString("MorethanSeate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại xin vui lòng kiểm tra lại đường dẫn !.
        /// </summary>
        public static string NonFileOpen {
            get {
                return ResourceManager.GetString("NonFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu trúc file access không đúng, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string NonFileStruct {
            get {
                return ResourceManager.GetString("NonFileStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Số dòng chưa được thực thi: .
        /// </summary>
        public static string NonSuccessData {
            get {
                return ResourceManager.GetString("NonSuccessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang ở cơ sở dữ liệu đăng kiểm!\n Nên không thể chuyển màn hình !.
        /// </summary>
        public static string NotChangeForm {
            get {
                return ResourceManager.GetString("NotChangeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn một mẫu tin !.
        /// </summary>
        public static string NotData {
            get {
                return ResourceManager.GetString("NotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không hợp lệ, xin vui lòng nhập lại !.
        /// </summary>
        public static string NotValidateTime {
            get {
                return ResourceManager.GetString("NotValidateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có số xe này.
        /// </summary>
        public static string Number_Vehicle {
            get {
                return ResourceManager.GetString("Number_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string Numbervehicle {
            get {
                return ResourceManager.GetString("Numbervehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ phương tiện.
        /// </summary>
        public static string Owners {
            get {
                return ResourceManager.GetString("Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn dừng cập nhật CSDL đăng kiểm không?.
        /// </summary>
        public static string PauseProgressBar {
            get {
                return ResourceManager.GetString("PauseProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chọn ngày!.
        /// </summary>
        public static string PleaseSelectDate {
            get {
                return ResourceManager.GetString("PleaseSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một dòng trên lưới dữ liệu !.
        /// </summary>
        public static string PleaseSelectInGrid {
            get {
                return ResourceManager.GetString("PleaseSelectInGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại dữ liệu.
        /// </summary>
        public static string PleaseTestData {
            get {
                return ResourceManager.GetString("PleaseTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá vé.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy chọn giá vé.
        /// </summary>
        public static string Price_Vehicle {
            get {
                return ResourceManager.GetString("Price_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT*FROM SUP_VehicleInformation.
        /// </summary>
        public static string QuerySQLAccess {
            get {
                return ResourceManager.GetString("QuerySQLAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.
        /// </summary>
        public static string QuerySQLConnectDatabase {
            get {
                return ResourceManager.GetString("QuerySQLConnectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng ký.
        /// </summary>
        public static string RegisDate {
            get {
                return ResourceManager.GetString("RegisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe quá dài !.
        /// </summary>
        public static string RegisLong {
            get {
                return ResourceManager.GetString("RegisLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe quá ngắn !.
        /// </summary>
        public static string RegisLost {
            get {
                return ResourceManager.GetString("RegisLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe không chứa ký tự đặc biệt!.
        /// </summary>
        public static string RegisNotSpecial {
            get {
                return ResourceManager.GetString("RegisNotSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe không hợp lệ. Vui lòng nhập lại!.
        /// </summary>
        public static string RegisNotValidate {
            get {
                return ResourceManager.GetString("RegisNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe không chứa ký tự đặc biệt!.
        /// </summary>
        public static string RegisPlateSpecial {
            get {
                return ResourceManager.GetString("RegisPlateSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tìm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm theo.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm phương tiện.
        /// </summary>
        public static string SearchVehicle {
            get {
                return ResourceManager.GetString("SearchVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chỗ là giá trị dương!.
        /// </summary>
        public static string SeatInteger {
            get {
                return ResourceManager.GetString("SeatInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chỗ.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Chọn.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu.
        /// </summary>
        public static string sess {
            get {
                return ResourceManager.GetString("sess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không được bỏ trống!.
        /// </summary>
        public static string SetDatePicker {
            get {
                return ResourceManager.GetString("SetDatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19000101.
        /// </summary>
        public static string SQL_MINDATE {
            get {
                return ResourceManager.GetString("SQL_MINDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu trúc dữ liệu file access không hợp lệ !.
        /// </summary>
        public static string StructDataFileAccessNotexception {
            get {
                return ResourceManager.GetString("StructDataFileAccessNotexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công !.
        /// </summary>
        public static string Success_Vehicle {
            get {
                return ResourceManager.GetString("Success_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật dữ liệu thành công !.  Số dòng thực thi được:  .
        /// </summary>
        public static string SuccessData {
            get {
                return ResourceManager.GetString("SuccessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cơ sở dữ liệu chuẩn.
        /// </summary>
        public static string Title_UpdateManagement {
            get {
                return ResourceManager.GetString("Title_UpdateManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cơ sở dữ liệu đăng kiểm.
        /// </summary>
        public static string Title_UpdateSatand {
            get {
                return ResourceManager.GetString("Title_UpdateSatand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cơ sở dữ liệu chuẩn.
        /// </summary>
        public static string TitleVehicleExpand {
            get {
                return ResourceManager.GetString("TitleVehicleExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng Mooc.
        /// </summary>
        public static string TRLgMooc {
            get {
                return ResourceManager.GetString("TRLgMooc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRLgMooc là giá trị dương !.
        /// </summary>
        public static string TRLGMoocInteger {
            get {
                return ResourceManager.GetString("TRLGMoocInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string TypeVehicle {
            get {
                return ResourceManager.GetString("TypeVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string TypeVehicleIsforce {
            get {
                return ResourceManager.GetString("TypeVehicleIsforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _D.
        /// </summary>
        public static string UI_Close_ShortKey {
            get {
                return ResourceManager.GetString("UI_Close_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có số xe này. Vui lòng kiểm tra lại !.
        /// </summary>
        public static string ValueExchange {
            get {
                return ResourceManager.GetString("ValueExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị không được vượt quá 9 chữ số !.
        /// </summary>
        public static string ValueThanMore {
            get {
                return ResourceManager.GetString("ValueThanMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSDL đăng kiểm.
        /// </summary>
        public static string VehicleInformation {
            get {
                return ResourceManager.GetString("VehicleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Cơ sở dữ liệu cục đăng kiểm.
        /// </summary>
        public static string VehicleInformationDetail {
            get {
                return ResourceManager.GetString("VehicleInformationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSDL chuẩn.
        /// </summary>
        public static string VehicleInformationManual {
            get {
                return ResourceManager.GetString("VehicleInformationManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải trọng.
        /// </summary>
        public static string VehicleLoad {
            get {
                return ResourceManager.GetString("VehicleLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng là giá trị dương !.
        /// </summary>
        public static string VehicleLoadInteger {
            get {
                return ResourceManager.GetString("VehicleLoadInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hiện tại chưa được lưu. Bạn có muốn lưu trước khi tiếp tục đóng?.
        /// </summary>
        public static string YesNoQuestion {
            get {
                return ResourceManager.GetString("YesNoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể xóa dữ liệu đăng kiểm !.
        /// </summary>
        public static string YouCannotdelete {
            get {
                return ResourceManager.GetString("YouCannotdelete", resourceCulture);
            }
        }
    }
}
